<style type="text/css">
	.bgSorryIE{position: fixed; left: 0px; right: 0px; bottom: 0px; top: 0px;}
	body{background: #fff; padding: 0px; margin: 0px; font-family: arial}
	a{text-decoration: none; }
	.btn{text-decoration: none; background:#ce1443; padding:10px 30px; font-size:20px; color: #fff; display: inline-block;}
	.loginCnt{position:fixed; top:50%; left:0%; margin-top:-150px; margin-left:0px; text-align: center; right: 0px;     padding: 30px; background: rgba(0, 0, 0, 0.1);}
	.brandlogo{width: 500px;margin:0 auto; display: block; height: 70px; background: url('<?php echo BASE_URL."/img/".$this->configuration->SigninImage; ?>') no-repeat; background-position: center center; background-size: contain; margin-bottom: 20px;}
</style>
<body id="frontPage2" >
	<?php echo $this->layout()->content; ?>	
</body>
</html>
