<link href="<?php echo BASE_URL."/css1/dbee.css";?>?v=<?php echo filemtime('css1/dbee.css');?>" rel="stylesheet" type="text/css" media="all"/>
<div class="emailVeryfingPage" id="pageContent">
<?php
if($this->AlreadyActivated==''){
?>
   <script language="javascript" type="text/javascript">
			setTimeout("window.parent.location='<?php echo BASE_URL ?>'",5000);
		</script>
	<div class="emailVerified"> 
		<h2  style="color:#99ba3f"> <i class="spirteVerified emailVerifiedIcon"> </i> Congratulations <strong><?php echo $this->full_name;?></strong>, your email has been verified.</h2>
		<p>You will be redirected to your homepage in 5 seconds. <a href="<?php echo BASE_URL ?>" class="normallinks">Click here</a> if you are not automatically redirected.</p>
	</div>
<?php 
}
if($this->AlreadyActivated){
?>

	<div class="emailVerified"> 
		<h2 style="color:#f20a0a"> <i class="spirteVerified emailNotVerifiedIcon"> </i> Error: This activation link is invalid or already used.</h2>
	</div>

<?php } ?>
</div>	