<script type="text/javascript" src="<?php echo BASE_URL."/adminraw/js/usergroup.js";?>"></script>
<script type="text/javascript">
userlist('promoted');
</script>
<div class="myAccountSocialConnect">
  <div class="responsiveTable">
    <table class="table-border userListTable table">
        <thead>
           <tr>
              <td colspan="1">
                 <div class="rpGraphTop clearfix" style="float: left; font-size:20px; margin-top:6px;">Promoted Expert</div>
                 <div style="float: right;">
                    <button class="btn btn-green fluidBtn pull-right" style="margin-right:0px;" type="button" onclick="fetchDbeeUser(this,'promoted');">
                    <i class="fa fa-plus fa-lg"></i>
                    Add more
                    </button>
                 </div>
              </td>
           </tr>
        </thead>
        <tbody>
           <tr>
              <td colspan='2'>
                 <div class="acntImgThumb userlist">
                     
                    
                    
                 </div>
              </td>
           </tr>
        </tbody>
     </table>
    </div>
</div>