<script type="text/javascript" src="<?php echo BASE_URL."/adminraw/js/jquery.js";?>"></script>
<script type="text/javascript" src="<?php echo BASE_URL."/adminraw/js/jquery-1.4.4.min.js";?>"></script>
<script type="text/javascript" src="<?php echo BASE_URL."/adminraw/js/jquery-1.9.1.js";?>"></script>
<script type="text/javascript" src="<?php echo BASE_URL."/adminraw/js/jquery-ui.js";?>"></script>
<script type="text/javascript" src="<?php echo BASE_URL."/adminraw/js/highcharts.js";?>"></script>
<script type="text/javascript" src="<?php echo BASE_URL."/adminraw/js/charts.js";?>"></script>
<script type="text/javascript" src="<?php echo BASE_URL."/adminraw/js/search.js";?>"></script>
<script type="text/javascript" src="<?php echo BASE_URL."/adminraw/js/userfunctions.js";?>"></script>
<script type="text/javascript" src="<?php echo BASE_URL."/adminraw/js/groupfunction.js";?>"></script>
<script type="text/javascript" src="<?php echo BASE_URL."/adminraw/js/knowledgecenter.js";?>"></script>

<input type="hidden" id="BASE_URL" name="BASE_URL" value="<?php echo BASE_URL;?>">
<div id="MiddleTopPost">
		<a href="/admin"><div id="Logo"></div></a>
		<div style="float:right">
			<a href="/myhome/logout"><div class="btn-logout"></div></a>
		</div>
</div>