<?php 
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('dbee.me | the debate n rate social network');

echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"> 
<head>
    <?php echo $this->headMeta(); ?> 
    <?php echo $this->headTitle(); ?>
    <?php //echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/site.css'); ?> 
	<?php echo $this->headLink()->prependStylesheet($this->baseUrl().'/css/styles.css'); ?> 
<link rel="icon" type="image/png" href="http://dbee.me/images/favicon.png">
<!--<link rel="stylesheet" href="css/styles.css" type="text/css" />-->

<!--[if gte IE 7]>  

	<link rel="stylesheet" type="text/css" media="all" href="css/ie7.css" />

<![endif]--> 

<!--[if gte IE 8]>  

	<link rel="stylesheet" type="text/css" media="all" href="css/ie8.css" />

<![endif]-->
</head>
<body>

<div id="Middle">

	<?php echo $this->render('header.phtml') ?>

	<div class="next-line"></div>

	<div id="MiddleContentArea">

		<?php /* <div id="MiddleLeft" style="padding-bottom:0px;">

			<div class="nav-tab icon-dashboard-bg" style="padding-top:0px">

				<div class="icon-dashboard"></div>

				<div class="nav-font" style="float:left"><a href="<?php echo $this->url(array('controller'=>'deshboard', 
            'action'=>'index'));?>" />Dashboard</a></div>

				<br style="clear:both; font-size:1px;" />

			</div>
			<div class="next-line"></div>
			
		</div> */ ?>
		<br style="clear:both; font-size:1px;margin-top:10px;" />
		<div class="next-line"></div>
		<div id="MiddleContentArea">
			
			 <?php echo $this->layout()->content; ?>

		</div>

	</div>

	<div class="next-line"></div>

</div>

<?php /*
<div id="content">
    <h1><?php echo $this->escape($this->title); ?></h1>
    <?php echo $this->layout()->content; ?>
</div> */?>
</body>
</html>