<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

  <title>db - Create Debate</title>


<style type="text/css">
body {
    background: #e6e6e6 none repeat scroll 0 0;
    font-family: Arial,Helvetica,sans-serif;
    font-size: 13px;
}
#pageContent {
    background: #e6e6e6 none repeat scroll 0 0;
    display: inline-block;
    padding: 20px;
    width: 100%;
}
.emailVerified {
    margin: 100px 0;
    text-align: center;
}
.emailVerified p {
    color: #666666;
    font-size: 20px;
}
.emailVerified h2 {
    font-size: 24px;
    font-weight: normal;
}
.emailVerified a {
    color: #0f97d0;
    text-decoration: underline;
}
a, a:hover {
    outline: medium none;
}
</style>
</head>

<body  id="pageContent">

  <?php 

  if($this->code=='404')
  { ?>
    
      <div id="pageContent" page-type="homepage" >
         <div >&nbsp;</div>
 
        <div  id="pageContent">
          <div style="width:160px; margin-left:auto; margin-right:auto;"></div>
 
           <script language="javascript" type="text/javascript">
           setTimeout("window.parent.location='<?php echo BASE_URL ?>/admin'",7000);
           </script>
         <div class="emailVerified"> 
          <h2 style="color:#99ba3f;"> Oops, something went wrong!</h2> 
          <p style="text-align: center; ">You will be redirected to dashboard in 5 seconds.  <a href="<?php echo BASE_URL ?>/admin" class="normallinks">Click here</a> if you are not automatically redirected.</p>
         </div>


         
        </div> 
      </div>

  <?php exit;  
  } else { ?>
      <div style="width:546px; margin-left:auto; margin-right:auto;"><img src="<?php echo BASE_URL ?>/images/img/brandLogo.png" width="546" height="375" /></div>
      <div style="font-family:Verdana, Arial, Helvetica, sans-serif; font-size:14px; color:#000000; text-align:center; width:1000px; margin-left:auto; margin-right:auto;">
        <p style="font-weight:bold; margin-bottom:10px"><strong>We are currently going through maintenance. Please check back in some time.</strong></p>
        <p style="font-weight:bold; margin-bottom:10px"><strong>Thank you for your patience :-)</strong></p>
        <!-- <p><a href="/">Click here to go back to home</a> </p> -->
      </div>

     <!--  <div id="error">
          <p>
              <ul class="errorList">
                  <li>
                      <h3><?php echo $this->message ?></h3> 
                  </li>
                  <li>
                      <h4>Exception information:</h4>
                      <p><?php echo $this->exception->getMessage() ?></p>
                  </li>
                  <li>
                      <h4>Stack trace:</h4>
                      <p><?php echo $this->exception->getTraceAsString() ?></p>
                  </li>
                   
              </ul>
          </p>
      </div> -->
<?php } ?>

</body>

</html>

