<script type="text/javascript">
$(document).ready(function(){
	$("#contactinfoid").click(function(){
                var fname =$("#fname").val();			
                if(fname==''||fname=='Name' ){
                     var msg1 ='please enter the name';
                     $("p.msg1").html(msg1);
                     return false;
               }    
		       var femail =$("#femail").val();
		       if(femail==''||femail=='Email'){
		             var msg2 ='please enter the email';
		             $("p.msg2").html(msg2);
		             return false;
		       } 
			   var password =$("#pass").val();
		       if(password==''||password=='Password'){
		             var msg3 ='please enter the password';
		             $("p.msg3").html(msg3);
		             return false;
		       }   
	})
});
function clickclear(thisfield, defaulttext) {
if (thisfield.value == defaulttext) {
thisfield.value = "";
}
}
function clickrecall(thisfield, defaulttext) {
if (thisfield.value == "") {
thisfield.value = defaulttext;
}
}
</script>
	
<?php
include("example.php");
?>