<?php

$return='';

$storage = new Zend_Auth_Storage_Session();

$data	= $storage->read();

$UserID  = $data['UserID'];

$userscore = new Application_Model_DbUser();

$getuserscoreinfo = $userscore->ausersocialdetail($UserID);



$return.='<div class="formRow" style="color:#dadada; font-size:14px; padding:10px;">Click on the link below to send yourself your password reset link. The link will be sent to the email address you used to register, this can be used once and will expire after you successfully reset your password.</div><div style="font-size:14px; margin-top:20px;" align="center"><a href="javascript:void(0)" rel="passreset-popup~350" class="poplight sendpassina" onclick="javascript:sendpass(1,'.$getuserscoreinfo[0]['UserID'].')">Send me a password reset link</a></div>';

$return.='<div id="forgotpass-message"></div>';



echo $return;

?>


