<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

<title>dbee.me | the debate n rate social network</title>

<meta name="description" content="db is a real time 'debate and rate' social network enabling you to share views on any subject, in open community or private groups. Create debate by posting opinions, photos, videos and links, score and be scored on posts, and rise or fall in db leagues.">

<meta property="og:url" content="http://www.dbee.me.com" /> 

<meta property="og:type" content="article" /> 

<meta property="og:title" content="dbee.me | the debate n rate social network" /> 

<meta property="og:site_name" content="db" /> 

<meta property="og:description" content="db is a real time 'debate and rate' social network enabling you to share views on any subject, in open community or private groups. Create debate by posting opinions, photos, videos and links, score and be scored on posts, and rise or fall in db leagues." /> 

<meta property="og:image" content="http://www.dbee.me/images/landing-logo.png" />

<link rel="icon" type="image/png" href="http://dbee.me/images/favicon.png">

<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => 'http://dbee.me/images/favicon.png'))

                       // ->prependStylesheet(BASE_URL . '/css/bootstrap-responsive.min.css')

                        ->prependStylesheet(BASE_URL . '/css/style.css')

                        ->prependStylesheet(BASE_URL . '/css/global.css')

                       // ->prependStylesheet(BASE_URL . '/css/bootstrap.min.css')

						->prependStylesheet(BASE_URL . '/css/speechbubbles.css')					

						->prependStylesheet(BASE_URL . '/css/ddcolortabs.css')					

						->prependStylesheet(BASE_URL . '/css/tabcontent.css')

						->prependStylesheet(BASE_URL . '/css/styles.css')

						->prependStylesheet(BASE_URL . '/css/dbee.css')						

						->prependStylesheet(BASE_URL . '/css/jquery.css')

						->prependStylesheet(BASE_URL . '/css/jquery.blockUI.css')

						->prependStylesheet(BASE_URL . '/css/shadowbox.css')

						->prependStylesheet(BASE_URL . '/css/dbee.css')						

						?>

<!-- Scripts -->



<?php echo $this->headScript()->prependFile(BASE_URL . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))

                     // ->prependFile(BASE_URL . '/js/bootstrap.min.js')

					  ->prependFile(BASE_URL . '/js/smooth.pack.js')

                      ->prependFile(BASE_URL . '/js/jquery.min.js')

				      ->prependFile(BASE_URL . '/js/functions.js')

				      ->prependFile(BASE_URL . '/js/browser_check.js')

				      ->prependFile(BASE_URL . '/js/ajaxupload.js')

				      ->prependFile(BASE_URL . '/js/jquery-latest.js')

				      ->prependFile(BASE_URL . '/js/jquery.min_1.4.4.js')

				      ->prependFile(BASE_URL . '/js/jquery.min_1.4.js')

				      ->prependFile(BASE_URL . '/js/jquery.slideto.v1.1.js')	

				      //->prependFile(BASE_URL . '/js/shadowbox/show_shadowbox.js')

				      //->prependFile(BASE_URL . '/js/shadowbox/shadowbox.js')				      

				      ->prependFile(BASE_URL . '/js/all.js')				

				      ->prependFile(BASE_URL . '/js/ddaccordion.js')

				      ->prependFile(BASE_URL . '/js/dropdowncontent.js')

				      ->prependFile(BASE_URL . '/js/dropdowntabs.js')	

				      ->prependFile(BASE_URL . '/js/html5.js')

				      ->prependFile(BASE_URL . '/js/javascript.js')

				      ->prependFile(BASE_URL . '/js/jquery.blockUI.js')

				      ->prependFile(BASE_URL . '/js/tabcontent.js')

				      ->prependFile(BASE_URL . '/js/speechbubbles.js')

				      ->prependFile(BASE_URL . '/js/jquery.js')

				      ?>

<script language="javascript" type="text/javascript">

var screenwidth = screen.width;

if (screenwidth == 1024) {

	document.write('<link rel="stylesheet" href="<?php echo BASE_URL.'/css/1024.css'?>" type="text/css" media="all" />');

}

</script>

<script language="javascript" type="text/javascript" src="<?php echo BASE_URL.'/js/functions.js?1379088342'?>"></script>

<script type="text/javascript" src="<?php echo BASE_URL.'/js/browser_check.js'?>"></script>

<script type="text/javascript" src="<?php echo BASE_URL.'/js/smooth.pack.js'?>"></script>

<!-- BEGIN INCLUDE SCRIPTS TO CALL SHADOWBOX -->

<script type="text/javascript" src="<?php echo BASE_URL.'/js/shadowbox/shadowbox.js'?>"></script>

<script type="text/javascript" src="<?php echo BASE_URL.'/js/shadowbox/show_shadowbox.js'?>"></script>

<!-- END INCLUDE SCRIPTS TO CALL SHADOWBOX -->

<!-- DROPDOWN CONTENT FOR MY GROUP OPTIONS -->

<script type="text/javascript" src="<?php echo BASE_URL.'/js/dropdowncontent/dropdowncontent.js'?>"></script>

<!-- DROPDOWN CONTENT FOR MY GROUP OPTIONS -->

<!-- DROPDOWN TOP MENU -->

<script type="text/javascript" src="<?php echo BASE_URL.'/js/dropdowntab/dropdowntabs.js'?>"></script>

<!-- DROPDOWN TOP MENU -->

<!-- BEGIN INCLUDE SCRIPTS TO CALL DHTML TOOLTIP -->

<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.'/css/speechbubbles.css'?>" />

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>

<script src="<?php echo BASE_URL.'js/speechbubbles.js'?>"></script>

<script type="text/javascript">

jQuery(function($){ //on document.ready

 $('.addspeech').speechbubble()

})

</script>

<script type="text/javascript" src="<?php echo BASE_URL.'/scripts/ajaxupload.js'?>"></script>

<script src="http://code.jquery.com/jquery-latest.js"></script>

<!-- SLIDING BACK TO TOP -->

<script language="javascript" type="text/javascript" src="<?php echo BASE_URL.'/js/jquery.slideto.v1.1.js'?>"></script>

<script language="javascript" type="text/javascript">

var jqnctop = jQuery.noConflict();

jqnctop(document).ready(function(){

	jqnctop('a[name=slidetotop]').slideto({

		target : '#pagetop',

		speed  : 700

	});

});

$(window).scroll(function(){

	if($(window).scrollTop() > 200 ){

		$('#backtotop').fadeIn("slow");

	} else if($(window).scrollTop() < 200 ){

		$('#backtotop').fadeOut("fast");

	}

});

</script>
<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.'/css/tabcontent.css'?>" />

<script type="text/javascript" src="<?php echo BASE_URL.'/js/tabcontent.js'?>"></script>

<script language="javascript" type="text/javascript">

$(function() {

	var open = false;

	$('#footerSlideButton').click(function() {

		if(open === false) {

			document.getElementById('footerSlideText').style.display='block';

			$('#footerSlideContent').animate({ height: '50px' });

			$(this).css('backgroundPosition', 'bottom left');

			open = true;

		} else {

			document.getElementById('footerSlideText').style.display='none';

			$('#footerSlideContent').animate({ height: '0px' });

			$(this).css('backgroundPosition', 'top left');

			open = false;

		}

	});

});

</script>
<link rel="stylesheet" href="<?php echo BASE_URL.'/css/whitebg.css'?>" type="text/css" />

<? if(isset($this->keyword) && isset($this->type) ) { ?>

<script language="javascript" type="text/javascript">

$(function() {

	searchgroups('<?=$this->keyword;?>','<?=$this->type;?>');

});

</script>

<? } ?>

</head>

<body>

<div style="clear:both"></div>

<!---------end header---------------------------->



<?

/*

if(isset($_COOKIE['user'])) {

    print_r($this->id);die;

	header('Location: recover2/id/'.$this->id);

	exit();

	

}

*/

?>



<script type="text/javascript">

<? if(isset($_GET['err'])) { ?>

window.onload = function() {

    // open a welcome message as soon as the window loads

    Shadowbox.open({

        content:    '<div class="login-err">Incorrect login details.<br /><br />Please login again.</div>',

        player:     "html",

        title:      "",

        height:     90,

        width:      300

    });

};



setTimeout("parent.Shadowbox.close()",4000);

<? } ?>

</script>

<link rel="stylesheet" href="<?php echo BASE_URL.'/css/whitebg.css'?>" type="text/css" />

</head>



<body>

<div id="wrapper">

	

	<div id="topWrapperIndex" class="topWrapperIndex">

		<div class="top">

		</div>

    </div>

    <div style="clear:both"></div>

	

	

	<div id="LandingMiddle" style="margin-top:10px;">

		<div>

			<div id="Logo" style="margin:0 0 20px 100px;"></div>

			<div class="next-line"></div>

			<div class="recover-wrapper">

				<div id="resetcode-wrapper" style="border:1px solid #999999;">

					<div class="recover-title">Enter password reset code</div>

					<div align="center" style="padding:10px;">

						<div>Password reset code&nbsp;&nbsp;<input type="text" id="resetcode" class="textfield" style="width:70px;"></div>

						<div class="next-line"></div>

						<div class="button" style="margin:10px 0 10px 0;" onClick="javascript:checkresetcode()">continue</div>

						<div id="resetcode-error" style="margin-bottom:10px;"></div>

					</div>

				</div>

				<div id="resetpass-wrapper" style="display:none; border:1px solid #999999;">

					<div class="recover-title">Reset your password</div>

					<div align="center" style="padding:10px;">

						<div style="float:left">New password</div>

						<div style="float:right"><input type="password" id="newpass" class="textfield" style="width:250px;"></div>

						<div class="next-line"></div>

						<div style="float:left; margin-top:10px;">Repeat new password</div>

						<div style="float:right; margin-top:10px;"><input type="password" id="newpassrepeat" class="textfield" style="width:250px;"></div>

						<div class="next-line"></div>

						<div class="button" style="margin:10px 0 10px 0;" onClick="javascript:resetpass()">reset</div>

						<div id="resetpass-error" style="margin-bottom:10px;"></div>

					</div>

				</div>

				<input type="hidden" id="user" value="<?php echo $this->id ; ?>">

				<div align="center" id="resetpass-msg-wrapper" style="display:none">Your have successfully changed your password.<br /><br />

				<a href="<?php echo BASE_URL ?>">Click here to go back to login.</a></div>

			</div>

		</div>

	</div>

</div>

</body>

</html>