
<div class="dbDetailsWrapper">

		<div class="dbDetailsContent">
					<div class="recover-wrapper" style="width:800px; font-size:14px;">

						<div id="resetcode-wrapper" style="border:0px solid #999999;">

							<div align="center" style="padding:10px;">You still seem to be logged into your account. You need to logout before you can proceed with password reset. After logging out, please click on the link below to go back to password reset.</div>

							<div align="center" style="padding:10px;"><a href="/index/recover/id/<?=$this->id?>">Take me to password reset</a></div>

						</div>

					</div>

				

	</div>
</div>


</body>

</html>


