<script type="text/javascript">
$(function() {
	
		var hashTag = window.location.hash
		var url = window.location.href;
		var hash = url.substring(url.indexOf('#'));  
		if(hash=="#msgsortprfilteraddcsv") {
			$messageSuccess('uploaded successfully');		                 
			$("#profanityFilterCloud").fadeIn();
			window.location.hash='';
		}  
	  $('body').on('keyup', '#searchfield', function(e){
		  if(e.keyCode==13){	  	
		    $('#wereew').trigger('click');
		  }
	  });
	  $('body').on('click','#resetwereew', function(e){
			e.preventDefault();			
			$('#sortprfilter').trigger('change');
			$('#searchfield').val('');
			
		});
	  $('body').on('click','#addprofil', function(e){
			e.preventDefault();
			var Profanityfilter1 = $('#Profanityfilter').val();
			Profanityfilter = Profanityfilter1.split(',');
			
			if(Profanityfilter=='' ){
				$messageError('Please add a word');
				return false;
			}
				$.ajax({
					url : BASE_URL+'/admin/dashboard/addprofanityfilter',
					data : {"word":Profanityfilter},
					type : "POST",
					dataType: "json",
					success: function(response){
		
						$messageSuccess('word added successfully');
						 $.each(response.vdata, function(i, value){
						var worfil = '<span id="grpid_'+value.id+'" class="dgrpUrsName" filterid="'+value.id+'">\
										<i>'+value.name+'</i>\
										<a class="removeCompare" href="javascript:void(0);">x</a>\
										</span>';
						$('.proCloundlist').append(worfil);
						 });

						 removeWordsPro ();
				

						 //var sntotal = parseInt($('#proCount').val(),10);
						$('#proCount').text(function(i,txt) { return parseInt(txt, 10) + response.total; });
						 
						      
						$('#Profanityfilter').val('');
						$("#profanityFilterCloud").fadeIn();  
						
					}
				});
		});
		
		$('body').on('click','#wereew', function(e){
			e.preventDefault();
			var searchfield = $('#searchfield').val();
			
			if(searchfield=='' ){
				$messageError('Please add a word to search');
				return false;
			}
			//$('.proCloundlist').append('<div class="loaderOverlay2"></div>');
			$dbLoader({element:'.proCloundlist',overlay:true});
			$.ajax({
				url : BASE_URL+'/admin/dashboard/profanityfilter',
				data : {"word":searchfield},
				type : "POST",
				dataType: "json",
				success: function(response){
					//$('.loaderOverlay2').remove();
					$('.proCloundlist').html(response.content);
					$('#proCount').html(response.total);
				//	$('.proCloundlist').hide();
					//$('#profanityFilterCloud').append(response.content);
					$('#resetwereew').fadeIn();
		
					removeWordsPro ();
							
				}
			});
		});
		
	function removeWordsPro (){
		 $('.proCloundlist  span .removeCompare').click(function  () {
		                var thisSelector = $(this);
		               var  wordTag = thisSelector.siblings('i').text();
		               var confirmD = '<div id="confirBox" title="Please confirm"><p>Are you sure you want to delete <strong>'+wordTag+'</strong>?</p></div>';
		               var filterid =  $(this).parent('span').attr("filterid");
		              
		                $('#confirBox').remove();
		                $('body').append(confirmD);
		                $('#confirBox').dialog({ 
		                   buttons: {
		                        "Yes": function() {                         
		                            var thisEl =$(this);                        
		                           thisSelector.closest('span').fadeOut('fast', function() {
		                                $(this).remove();
		                                 thisEl.dialog( "close" );
		                            });                   
		                            $.ajax({
		                                type : "POST",
		                                dataType : 'json',
		                                url : BASE_URL + '/admin/dashboard/profanitydelete',
		                                data:{'filterID':filterid},   
		                                success : function(response) {                                      
		                                  $('#proCount').html(response.total);                             
		                                  $messageSuccess("removed successfully");
										  $('#proCount').text(function(i,txt) { return parseInt(txt, 10) + -1; });
		                                   thisEl.dialog( "close" );
		                                   
		                                },
		                                error : function(error) {
		                                    $messageError("Some problems have occured. Please try again later: "+ error);                      
		                                }                               
		                               });
		                        }
		                      }
		                  });
		          
		         });
	}	
	$('body').on('click','#viewexisting',function(){
		$("#profanityFilterCloud").fadeToggle();
		$("#viewexisting").text($("#viewexisting").text() == "View existing words" ? "Hide existing words" : "View existing words");
	});
	
	$('body').on('change','#sortprfilter',function(){
	
		var sortprfilter = $('#sortprfilter').val();
	
		$dbLoader({element:'.proCloundlist',overlay:true});
		$.ajax({
				url : BASE_URL+'/admin/dashboard/profanityfilter',
				data : {"orderfield":sortprfilter},
				type : "POST",
				dataType: "json",
				success: function(response){
					$('.proCloundlist').html(response.content);
					$('#proCount').html(response.total);
					$('#resetwereew').fadeOut();
					$('.proCloundlist  span .removeCompare').click(function  () {
		                var thisSelector = $(this);
		               var  wordTag = thisSelector.siblings('i').text();
		               var confirmD = '<div id="confirBox" title="Please confirm"><p>Are you sure you want to delete <strong>'+wordTag+'</strong>?</p></div>';
		               var filterid =  $(this).parent('span').attr("filterid");
		              
		                $('#confirBox').remove();
		                $('body').append(confirmD);
		                $('#confirBox').dialog({ 
		                    buttons: {
		                        "Yes": function() {                         
		                            var thisEl =$(this);                        
		                           thisSelector.closest('span').fadeOut('fast', function() {
		                                $(this).remove();
		                                 thisEl.dialog( "close" );
		                            });                   
		                            $.ajax({
		                                type : "POST",
		                                dataType : 'json',
		                                url : BASE_URL + '/admin/dashboard/profanitydelete',
		                                data:{'filterID':filterid},   
		                                success : function(response) {                                      
		                                  $('#proCount').html(response.total);                             
		                                  $messageSuccess("removed successfully");
										  $('#proCount').text(function(i,txt) { return parseInt(txt, 10) + -1; });
		                                   thisEl.dialog( "close" );
		                                   
		                                },
		                                error : function(error) {
		                                    $messageError("Some problems have occured. Please try again later: "+ error);                      
		                                }                               
		                               });
		                        }
		                      }
		                  });
		          
		         });
				}
			});
	});
});
</script>
<?php
$this->title = "Profanity filter";
$this->headTitle ( $this->title );

?>
<h1 class="pageTitle ">Profanity / keyword filter</h1>
<div class="pageSubeTitlevip">Add any abusive language or keywords you
	wish to be restricted completely from the platform.</div>

<div class="buttonProfanity">
<div class="dropDown pull-left">
	<a class="btn btn-yellow dropDownTarget" href="#"><i
		class="fa fa-file-excel-o fa-lg"></i> Upload CSV</a>
	<div class="dropDownList ">
		<form enctype="multipart/form-data"
			action="<?php echo BASE_URL;?>/admin/import/getcsvrecords"
			id="formid" method="POST">
			<div class="formRow">
				<div class="appendType">
					<input type="text" readonly="" name="" class="uploadType"> <a
						href="javascript:void(0);" class="btn btn-black">Browse <input
						type="file" id="addusers" name="csvfile" class="fileType"></a>
				</div>
			</div>
			<div class="formRow">
				<button class="btn btn-green fluidBtn" value="ADD FILTER WORD"
					id="csv_submit" name="csv_submit" type="submit">
					<i class="fa fa-plus fa-lg"></i> Upload CSV
				</button>
			</div>
			<div class="formRow">
				<a class="pull-right link"
					href="/downloadcenter/importfilterformat.csv"> <i
					class="fa-download-alt fa-lg"></i> Click Here to Download Example
				</a>
				<div style="clear: both"></div>
				<!-- <div class="subText">
					<i class="fa-info-sign"></i> Upload a CSV with multiple word
				</div> -->
				<input type="hidden"  name="frmidfilterprofinalty" id="frmidfilterprofinalty" value="1" class="uploadType">
			</div>
			<div class="clearfix"></div>
		</form>
	</div>
</div>


<div class="dropDown  pull-left fillbtntwo">
	<a href="#" class="btn btn-yellow dropDownTarget"><i
		class="fa fa-plus fa-lg"></i> Add new word</a>
	<div class="dropDownList left">

		<form class="right" action="#" method="POST">
			<div class="formRow" style="padding: 0px;">
				<label class="label">Enter word :</label>
				<div class="field">
					<input type="text" id="Profanityfilter" name="ProfanityfilterInput">
					<div class="subText">
						<i class="fa-info-sign"></i> Separate multiple words with a comma
					</div>
				</div>
			</div>

			<div class="formRow" style="padding: 0px;">
				<label class="label"></label>
				<div class="field">
					<button type="button" class="btn btn-green fluidBtn addprofil"
						id="addprofil">
						<i class="fa fa-plus fa-lg"></i> Add
					</button>
				</div>
			</div>
		</form>

	</div>
</div>
<a href="#" class="btn dropDownTarget fillbtntwo"	id="viewexisting">View existing words</a>
</div>
<div class="userUpBar">
	<!-- <div class="userSearchBox">
							<div class="appendType  pull-left">	
								<form action="<?php //echo $this->url(array('controller'=>'dashboard','action'=>'profanityfilter'));?>" method="POST">
									<input type="text" placeholder="Search existing restricted words" id="searchfield" name="searchfield"> 
									<button class="btn btn-black" id="submit" name="submit" type="submit">Search</button>
								</form>			
								<div class="clearfix"></div>
							</div>
						</div> -->
	<div class="pull-right buttonRight">

		<!-- <div class="dropDown pull-left">
								<a class="btn dropDownTarget" href="#"><i class="fa fa-file-excel-o fa-lg"></i> Add words from CSV</a>
								<div class="dropDownList right">									
									<form enctype="multipart/form-data" action="/home/import/getcsvrecords" id="formid" method="POST">
										<div class="formRow">
											<div class="appendType">
												<input type="text" readonly="" name="" class="uploadType">
												<a href="javascript:void(0);" class="btn btn-black">Browse <input type="file" id="addusers" name="csvfile" class="fileType"></a>
											</div>
										</div>
										<div class="formRow">
										<button class="btn btn-green fluidBtn" value="ADD FILTER WORD" id="csv_submit" name="csv_submit" type="submit">
											<i class="fa fa-plus fa-lg"></i> Add
										</button>
										</div>
										<div class="formRow">
											<a class="pull-right link" href="/downloadcenter/importfilterformat.csv">
												<i class="fa-download-alt fa-lg"></i> Click Here to Download Example
											</a>
											<div style="clear:both"></div>
											<div class="subText"><i class="fa-info-sign"></i> Upload a CSV with multiple word</div>
										</div>
										<div class="clearfix"></div>
									</form>
								</div>
							</div> -->

	</div>
</div>

<div class="clearfix"></div>



<div id="profanityFilterCloud" class="kcRightPanel" style="width: 100%;">

	<div class="kcRightHeader clearfix">
		<div class="clearfix">
			<h2 class="pull-left"  style="margin: 8px 5px 0 10px">Total: <span id="proCount"><?php echo count($this->data); ?></span></h2>
			<div class="searchprofil">

				<input type="text" placeholder=""
					id="searchfield" name="searchfield">
				<div class="btn btn-black" id="wereew" name="submit" type="button">Search</div><span class="btn btn-gray" id="resetwereew" >Reset</span>

			</div>
			<div class="search pull-right">

				<select class="gh-tb " maxlength="200" value="" id="sortprfilter"
					name="orderfield">
					<option value="0">- Sort Results -</option>
					<option value="1"
						<?php if($orderfield==1) { echo "selected=\"selected\" "; } ?>>
						Alphabetically A-Z</option>
					<option value="2"
						<?php if($orderfield==2) { echo "selected=\"selected\" "; } ?>>
						Alphabetically Z-A</option>
				</select>


			</div>

		</div>
	</div>
	<div class="proCloundlist">
			<?php
			if (count ( $this->data ) > 0) {
				foreach ( $this->data as $row ) :
					?>
				<span filterId="<?php echo $this->escape($row['id']);?>"
			class="dgrpUrsName"
			id="grpid_<?php echo $this->escape($row['id']);?>"> <i><?php echo $this->escape($row['name']);?></i>
			<a class="removeCompare" href="javascript:void(0);">x</a>
		</span>
			<?php
				
endforeach
				;
			} else {
				echo '<div class="dashBlockEmpty">No records found</div>';
			}
			?>
			
		</div>

</div>
