<div id="passform" class="postTypeContent locationWrpCnt" style="margin-bottom:30px;">
	<div class="formRow">
		<div class="formField">
			<input type="text" name="countryauto" id="countryauto" class="" value="">
			<i class="optionalText">Country</i>
		</div>
	</div>
	<div id="select2address">
		<div class="formRow">
			<div class="formField">
				<input type="text" name="countryAddrss" id="countryAddrss" class="" value="">
				<i class="optionalText">Address</i>
			</div>
		</div> 
	</div>
</div>	



