<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
   // Load the Visualization API and the piechart package.
   
   google.load('visualization', '1.0', {'packages':['corechart']});
   
   function drawChart(opt1,opt2,opt3,opt4,opt1num,opt2num,opt3num,opt4num,totalvotes) {         
   
   opt4 = typeof(opt4) != 'undefined' ? opt4 : '-1';  
   
     // Create the data table.
   
     var data = new google.visualization.DataTable();
   
     data.addColumn('string', 'Option');
   
     data.addColumn('number', 'Slices');
   
   if(opt4!='-1') {
   
   data.addRows([
   
   [opt1,parseInt(opt1num)],
   
   [opt2,parseInt(opt2num)],
   
   [opt3,parseInt(opt3num)],
   
   [opt4,parseInt(opt4num)]
   
   ]);
   
   } else {
   
   data.addRows([
   
   [opt1,parseInt(opt1num)],
   
   [opt2,parseInt(opt2num)],
   
   [opt3,parseInt(opt3num)]
   
   ]);
   
   }    
     // Set chart options
     var options = { is3D: true,
       chartArea:{left:0,top:0,width:"100%",height:"100%"},
       legend: {position: 'none'},
       fontSize:'16',
       backgroundColor:'transparent',
        chartArea: {
            left: "43%",
            top: "3%",
            height: "94%",
            width: "94%"
        }
       };
     // Instantiate and draw our chart, passing in some options.
   
     var chart = new google.visualization.PieChart(document.getElementById('PollPieChart'));
     if(totalvotes>0)
      chart.draw(data, options);    
   
   }
</script>