<?php 
	 $counter = 1; foreach ($this->qaResult as $row): 

		$ago = $this->common_model->Commentagohelper($row['timestamp']);
		 if ($row['user_id'] != '-1') 
		 {
	        if ($row['Status'] == 1)
	            $profilelinkstart = '<a href="' . BASE_URL . '/user/' . $this->myclientdetails->customDecoding($row['Username']) . '" class="cmntuserLink">';
	        else 
	            $profilelinkstart = '<a href="javascript:void(0)" class="profile-deactivated" title="' . DEACTIVE_ALT . '" onclick="return false;">';
	        $profilelinkend = '</a>';
			$userTypenal = $this->common_model->checkuserType($row['usertype']);
	    } 
	    else 
	    {
	        $profilelinkstart = '';
	        $profilelinkend   = '';
	    }
	    if ($counter % 2 == 0)
            $oddeven = 'commenteven';
        else
            $oddeven = 'commentodd';
        $divcontainer = '';
        if ($row['reply'] == 1) 
		{ 
            $parentDiv = $this->expert_model->getallanswersfromcommentidQA($row['id'],$this->expertText);
            if($parentDiv!='')
            {
            	$divcontainer = '<div class="parentcomment" >' . $parentDiv . '</div>';
            	$propqa = ' propqa ';
        	}
        }
        
        if($this->singleRow=='no')
			$return .= '<div id="comment-block-question-' . $row['id'] . '" class="comment-list ' . $oddeven . '" ' . $no_bottom_border . '>';

		$return .='<div style="float:left; width:40px; height:40px;">' . $profilelinkstart . '<img src="'.IMGPATH.'/users/small/' . $row['ProfilePic'] . '" border="0" width="30" height="#0" />' . $profilelinkend . '</div>';
		$return .= '<div id="dbcomment-speechwrapper" class="dbcomment-speechwrapper"><div class="cmntPrpLnks '.$propqa.'">' . $profilelinkstart . $this->myclientdetails->customDecoding($row['Name']) . ' ' . $this->myclientdetails->customDecoding($row['lname']) . $userTypenal . $profilelinkend;
		$return .= '&nbsp;' . $this->comment_model->convert_clickable_links($row['qna']) . '</div>';
        $return .=$divcontainer;
        $return .= '</div>';
        $expertData = $this->User_Model->getUserDetail($row['expert_id']);
	    $fullname = '';
	    
	    if($this->loginUserId == $row['expert_id'])
	    {
	    	$fullname = ' for '.'<a href="' . BASE_URL . '/user/' . $this->myclientdetails->customDecoding($expertData['Username']) . '" class="cmntuserLink">'.$this->myclientdetails->customDecoding($expertData['Name']) . ' ' . $this->myclientdetails->customDecoding($expertData['lname']).'</a>';
	    }

		$return .= '<div class="next-line"></div><div class="ftrCmnt"><div style="float:left;">' . $ago . $fullname.'</div>';
	
		if ($row['reply']== 0 && $this->loginUserId == $row['expert_id'] && $this->loginUserId!='') 
		{   
			$return .= '<div style="float:right; margin-left:2px;"><a href="javascript:void(0);" class="replytoquestion btn btn-mini btn-green" expert_id="' . $row['expert_id'] . '" cmntowner="' . $row['UserID'] . '" dbid="' . $row['dbeeid'] . '" commentID="' . $row['id'] . '">Answer</a></div>';/*
			if($row['expert_id'] == $this->loginUserId && $this->loginUserId == $this->ownerid)
				$return .= '<div class="qalinks" id="qalinks_'.$row['id'].'" ><div style="float:right; margin-left:2px;"><a href="javascript:void(0);" data-type="movetohide" class="movetoexpert btn btn-mini" dbid="' . $row['dbeeid'] . '" commentID="' . $row['id'] . '">Remove</a></div></div>';*/
			$return .= '<div class="replymebox" id="replymebox' . $row['id'] . '"></div>';			
		}else
			$return .= '<br style="clear:both;font-size:1px;" /></div>';
			
		if($this->singleRow=='no')
				$return .= '</div>';

		$return .= '</div><div class="next-line"></div></div>';
	$counter++; endforeach;  
	echo $return; 
?>