<?php /* echo $this->providerscategory ?>
<script>

	//chartforemailproviders(<?php echo $this->providersdata ?>,'emailreportchart',"Email Providers Sources");

	$("document").ready(function(){

		chartforbrowsersproviders(<?php echo $this->providersdata ?>,<?php echo $this->providerscategory?>,'browserprovidercontainer',"Browsers Providers Sources");
	});

</script>

<h1 class="pageTitle">Browsers Reporting </h1>

<div id="browserprovidercontainer" style="min-width: 400px; float:left; height: 400px; margin: 0 auto"></div>

<div id="browserusers" style="float:right;min-width: 500px; height: 500px; margin: 0 auto; overflow:auto; position:relative"></div>
