<form method="POST" action="">
Encoded value : <input type="text" name="fieldname" value="<?php echo $this->fieldnamePost; ?>" /> 
encoded value output :<?php echo $this->fieldname; ?> <br />
Decoded value : <input type="text" name="fieldname2" value="<?php echo $this->fieldnamePost2; ?>" /> 
Decoded value output :<?php echo $this->fieldname2; ?><br />
<input type="submit" value="submit" name="submit"> 
<br />
</form>

