<script>
$(function() {
 fetchadvert();
 loadmygroups('<?php echo $this->userid ;?>',<?php echo $this->member;?>);	
 dashboardprofile('<?php echo $this->userid;?>',1);
	$('#toggle-twitter-asearch').click(function(){
		$(".slidingTwitterSearch").slideToggle('fast');
		if(document.getElementById('toggle-twitter-asearch').className=='twitter-search-arrow-closed')
			document.getElementById('toggle-twitter-asearch').className='twitter-search-arrow-open';
		else
			document.getElementById('toggle-twitter-asearch').className='twitter-search-arrow-closed'
	});
	// initialize twitter advanced search options
});

// Create the tooltips only on document load
function createdrop(start,end) {
	for(i=start;i<=end;i++) {
		dropdowncontent.init("scorecomment"+i, "left-bottom", 100, "mouseover");
	}
}
	$(window).scroll(function(){
		//var feedtype=document.getElementById('feedtype').value;
		if  ($(window).scrollTop() == $(document).height() - $(window).height()) {
			if(feedtype=='mydbs') {
				var totaldbees=document.getElementById('totaldbees').value;
				if(totaldbees>5) {
					var mystart=document.getElementById('startnewmydb').value;
					seemoremyfeeds(mystart,5);
				}
			}
			else if(feedtype=='myredbs') {
				var totalredbees=document.getElementById('totalredbees').value;
				if(totalredbees>5) {
					var mystart=document.getElementById('startnewmyredb').value;
					seemoremyfeeds(mystart,5); 
				}
			}
			else if(feedtype=='mycomments') {
				var mystart=document.getElementById('startnewmycomments').value;
				seemoremycomments(mystart,5,<?php echo $this->userid;?>);
			}
		}
	});
</script>

<script>


// Create the tooltips only on document load
function load_qtip(apply_qtip_to)
{
   // Notice the use of the each() method to acquire access to each elements attributes
   $(apply_qtip_to).each(function()
   {
      $(this).qtip({
         content: $(this).attr('tooltip'), // Use the tooltip attribute of the element for the content
         style: 'dark' // Give it a crea mstyle to make it stand out
      });
   });
}
</script>

<input type="hidden" id="profileuser" value="<?php echo $this->userid;?>">

<?php 
	$mem = ($this->member==1)?'member of group':'my group'
?>
	<div id="leftListing">
		<div class="dashboarprofleWrp" id="dashboarduserDetails"></div>		
		<ul class="postListing" id="my-dbees"></ul>		
	</div>
	<div id="rightListing" class="rssFeedRightContainer" style="">		
		<div class="whiteBox">
		<h2>Upcoming Event<a href="#">View...</a></h2>
		<img src="<?php echo BASE_URL;?>/img/addver.png">
		</div>
	
	
	</div>
	<div class="clearfix"></div>

<div class="clear:both"> </div> 
<!--End page listing-->

