<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title><?php echo $this->title; ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <link href="<?php echo URL."/css1/dbee.css";?>?v=<?php echo filemtime('css1/dbee.css');?>" rel="stylesheet" type="text/css" media="all"/>
    <?php if($this->session_data['UserID']!=''){?>
			<link href="<?php echo URL."/plateformcss";?>" rel="stylesheet" type="text/css" media="all"/>	
		<?php } ?>
</head>

<body>
	<div class="bgCover"><img src="<?php echo BASE_URL; ?>/event/<?php echo $this->bgimage; ?>"/></div>
	<div id="splashWrp">
			<div class="splashCnt">
				<div class="splashCenter">
					<h1><?php echo $this->title; ?></h1>
					<div class="eventVenue"> <?php if($this->address!='') echo '<p><i class="fa fa-map-marker"></i>  '.$this->address.'</p>'; ?>
			          <?php if($this->start!='') echo "<p>".date('\<\s\p\a\n \c\l\a\s\s\=\"\d\a\t\e\p\a\n\"\>\<\i \c\l\a\s\s\=\"f\a\ \f\a\-\c\a\l\e\n\d\a\r\"\>\<\/\i\>d M Y<\/\s\p\a\n\> \<\s\p\a\n \c\l\a\s\s\=\"\t\i\m\e\p\a\n\"\>\<\i \c\l\a\s\s\=\"\f\a \f\a\-\c\l\o\c\k\-\o\"\>\<\/\i\> h:i A\<\/\s\p\a\n\>', strtotime($this->start))."</p>"; ?>
			          <span class="splashTo">To</span>
			          
			          <?php if($this->end!='') echo "<p>".date('\<\s\p\a\n \c\l\a\s\s\=\"\d\a\t\e\p\a\n\"\>d M Y<\/\s\p\a\n\> \<\s\p\a\n \c\l\a\s\s\=\"\t\i\m\e\p\a\n\"\>h:i A\<\/\s\p\a\n\>', strtotime($this->end))."</p>"; ?>
			          <?php if($this->timezoneevent!='') echo '<p>Time zone: '.$this->timezoneevent.'</p>'; ?>
			      </div>

			      <div class="enterWrp">
		          	<a class="btn" style="padding:10px" href="javascript:void(0);">Enter Event</a>
		          </div>
				</div>

				
			</div>
	</div>
</body>
</html>