<?php   
	
$commonbynew 	=	new Application_Model_Commonfunctionality();

    $IDs = '';   
    $startnew =$this->startnew;     
$dbeeList = array();
    if(count($this->dbeealldbees) > 0) {
	 $k=1;        
	 if(strlen($row->Text)>250) $dots='...'; else $dots='';
     if($k=='1' && $initial=='1') setcookie("CookiePostDate", $row->PostDate, time()+3600);         

	    foreach ($this->dbeealldbees as $row) :
	     	$IDs .= $row['DbeeID'].',';
	     $slice = array();
		if($row['TaggedUsers']!="")
		{
		 $slice=explode(',', $row['TaggedUsers']);
	    }
		
		if(count($slice) > 0 && $this->session_data['UserID']!=$row['User'] && $row['PrivatePost']==1)
		{
			if(in_array($this->session_data['UserID'], $slice))
	        {
	     	$return.=$commonbynew->displayLayoutDbs($row,$this->Social_Content_Block,'all',$this->plateform_scoring,$this->adminpostscore);
	       }
	    }
	    else
	    {
	      $return.=$commonbynew->displayLayoutDbs($row,$this->Social_Content_Block,'all',$this->plateform_scoring,$this->adminpostscore);
	    }
			$k++;
			$dbeeList[] = $row['DbeeID'];
	    endforeach; 

	}	
	else {
		//$seemorelabel='- no more '.POST_NAME.'s available to show -';
	}
$IDs=substr($IDs,0,-1);			

$return.='<div id="see-more-feeds'.$startnew.'"><div id="more-feeds-loader" style="cursor:pointer; color:#333333; text-align:center;" onclick="javascript:seemorefeeds('.$startnew.',15);">'.$seemorelabel.'</div></div>';

echo $return.'~#~'.$end.'~#~'.$IDs.'~#~'.$startnew.'~#~'.implode(',', $dbeeList);

			

			 ?>