
<link href="<?php echo BASE_URL."/css1/dbee.css";?>?v=<?php echo filemtime('css1/dbee.css');?>" rel="stylesheet" type="text/css" media="all"/>
	<div class="pageCenter noLayoutWrapper" id="pageContent">
	<script language="javascript" type="text/javascript">
		setTimeout("window.parent.location='<?php echo $this->redirect; ?>'",5000);
	</script>
	<div class="emailVerified"> 
		<h2  style="color:#99ba3f"> <i class="spirteVerified emailVerifiedIcon"> </i> You are being redirected back to the page</h2>
		<p><a href="<?php echo $this->redirect; ?>" class="normallinks">Click here</a> if you are not automatically redirected.</p>

	</div>
</div>


