<link href="/min/?f=/css1/font-awesome-4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" media="all"/>
<style type="text/css">
  *{box-sizing:border-box; -webkit-box-sizing:border-box; -moz-webkit-box-sizing:border-box;}
  body{background: #E4E4E4; margin: 0px; padding: 0px;}
  .centerBox{position: fixed; top: 50%; text-align: center; width: 100%;  min-height: 100px; margin-top: -50px;    background: rgba(255,255,255,1)}
  .brandLogo{text-align: center;}
  .emailVerified{color: #8bbc21;  font-family: arial; font-weight: normal;}
  .animated {
      -webkit-animation-duration: 1s;
      animation-duration: 1s;
      -webkit-animation-fill-mode: both;
      animation-fill-mode: both;
      -webkit-animation-delay: 3s; /* Chrome, Safari, Opera */
      animation-delay: 3s;
    }
  @-webkit-keyframes fadeOutDown {
  0% {
    opacity: 1;
    -webkit-transform: translateY(0);
    transform: translateY(0);
  }

  100% {
    opacity: 0;
    -webkit-transform: translateY(20px);
    transform: translateY(20px);
  }
}

@keyframes fadeOutDown {
  0% {
    opacity: 1;
    -webkit-transform: translateY(0);
    -ms-transform: translateY(0);
    transform: translateY(0);
  }

  100% {
    opacity: 0;
    -webkit-transform: translateY(20px);
    -ms-transform: translateY(20px);
    transform: translateY(20px);
  }
}

.fadeOutDown {
  -webkit-animation-name: fadeOutDown;
  animation-name: fadeOutDown;
}

</style>

<div id="pageContent" page-type="homepage" >
   <div >&nbsp;</div>
  <div  id="pageContent">
      <div class="centerBox fadeOutDown animated">
      <h2 class="emailVerified"> 
        <span class="fa-stack fa-lg">
          <strong class="fa fa-circle-thin fa-stack-2x"></strong>
          <strong  class="fa fa-check fa-stack-1x "></strong>
 </span>
    You are being redirected to your platform
      </h2>
    </div>
  </div> 
</div>
<?php if($this->type=='twitter') { ?>
<script language="javascript" type="text/javascript">
setTimeout("window.parent.location='<?php echo BASE_URL ?>/twitter/admin?refer=configuration'",3000);
</script>
<?php }else if($this->type=='linkedin') {?>
<script language="javascript" type="text/javascript">
setTimeout("window.parent.location='<?php echo BASE_URL ?>/social/adminlinkedin?refer=configuration'",3000);
</script>
<?php }else{ ?>
<script language="javascript" type="text/javascript">
document.location.reload();
setTimeout("window.parent.location='<?php echo BASE_URL ?>'",3000);
</script>
<?php } ?>