<?php
/*
 * Search pagination
 */ 
?>

<?php 
if ($this->pageCount): 
  $params=Zend_Controller_Front::getInstance()->getRequest()->getParams();
  unset($params['controller']);
  unset($params['action']);
  unset($params['module']);
?>
<div id="paginnationWrapper"><ul id="pagination">
<?php if (isset($this->previous)): ?>
<li><a href="<?php echo $this->url(array('page' => $this->previous)); ?>"> Back</a></li>
	<?php else: ?>
<li class="previous-off"> Previous</li>
<?php endif; ?>
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
<li><a href="<?php echo $this->url(array_merge($params,array('page'=>$page))); ?>"><?php echo $page; ?></a></li>
<?php else: ?>
<li class="active"><a href="<?php echo $this->url(array_merge($params,array('page'=>$page))); ?>"><?php echo $page; ?></a></li>
  <?php endif; ?>
<?php endforeach; ?>
<!-- Next page link -->
<?php if (isset($this->next)): ?>
<li class="next"><a href="<?php echo $this->url(array('page' => $this->next)); ?>"> Next </a></li>
<?php else: ?>
 <li class="next-off">Next </li>
<?php endif; ?>
</ul></div>
<?php endif; ?>



<?php 
/*
 * Item pagination example
 * 
 */
?>

<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=itempagination
-->

<?php /*if ($this->pageCount): ?>
<div class="paginationControl">
<?php echo $this->firstItemNumber; ?> - <?php echo $this->lastItemNumber; ?>
of <?php echo $this->totalItemCount; ?>

<!-- First page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->first)); ?>">
    First
  </a> |
<?php else: ?>
  <span class="disabled">First</span> |
<?php endif; ?>

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
    &lt; Previous
  </a> |
<?php else: ?>
  <span class="disabled">&lt; Previous</span> |
<?php endif; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
    Next &gt;
  </a> |
<?php else: ?>
  <span class="disabled">Next &gt;</span> |
<?php endif; ?>

<!-- Last page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->last)); ?>">
    Last
  </a>
<?php else: ?>
  <span class="disabled">Last</span>
<?php endif; ?>

</div>
<?php endif; */?>

<?php
/*
 * Drop down paginaton example
 */
?>
<?php /* if ($this->pageCount): ?>
<select id="paginationControl" size="1">
<?php foreach ($this->pagesInRange as $page): ?>
  <?php $selected = ($page == $this->current) ? ' selected="selected"' : ''; ?>
  <option value="<?php
        echo $this->url(array('page' => $page));?>"<?php echo $selected ?>>
    <?php echo $page; ?>
  </option>
<?php endforeach; ?>
</select>
<?php endif; */ ?>

<?php /* 
<script type="text/javascript"
     src="<?php echo BASE_URL."js/prototype.js";?>">
</script>

<script type="text/javascript">
$('paginationControl').observe('change', function() {
    window.location = this.options[this.selectedIndex].value;
})
</script>
*/ ?>