<div class="bgSorryIE" style=" background:#E6E6E6 url('<?php echo BASE_URL."/img/".$this->configuration->loginbackgroundimage; ?>') no-repeat; background-size:cover; background-position:center center "></div>

<div class="loginCnt">
	<div class="brandlogo"></div>
	<a href="https://dev04-web-onlinegolf.demandware.net/s/AmericanGolf-GB/account-edit?token=1&url=https://americangolfclub.onserro.com/aglogin/index/callback" class="btn">Login</a>
	<a href="https://dev04-web-onlinegolf.demandware.net/s/AmericanGolf-GB/account-edit?register=true&token=1&url=https://americangolfclub.onserro.com/aglogin/index/callback" class="btn">Registration</a>
</div>