<style type="text/css">
	body{background: #fff; padding: 0px; margin: 0px; font-family: arial}
	a{text-decoration: none; }
	.btn{text-decoration: none; background:#ce1443; padding:10px 30px; font-size:20px; color: #fff}
	.loginCnt{position:fixed; top:50%; left:50%; margin-top:-150px; margin-left:-120px; text-align: center;}
	.brandlogo{width: 300px; height: 140px; background: url('<?php echo BASE_URL."/img/".$this->configuration->SiteLogo; ?>') no-repeat; background-position: center center; background-size: contain; margin-bottom: 20px;}
</style>
<body id="frontPage2" >
	<?php echo $this->layout()->content; ?>	
</body>
</html>
