<script type="text/javascript" src="<?php echo BASE_URL; ?>/adminraw/js/jquery.tokeninput.js"></script>
<link rel="stylesheet" href="<?php echo BASE_URL; ?>/adminraw/css/token-input.css" type="text/css" />
<link rel="stylesheet" href="<?php echo BASE_URL; ?>/adminraw/css/token-input-facebook.css" type="text/css" />


<script>
$(function(){
  $('body').on('click','.ViewAllClickedUsers a.btn-mini', function(){
    
    
    var bannerid = '';
    var gaobj = $(this);
    var bannerid = $(this).attr('data-bannerid');
    
     $( "#surveyDialog1" ).remove();

    var htmlLightbox = '<div id="surveyDialog1"  title="Platform users"><div id="grouplist"></div>\
      <div id="userInfoContainer"></div>\
              </div>';
    var checkHtml = '<label class="surveychkall">\
              <input type="checkbox" value="1" id="grpchkall" class="goupuser" name="commentduring" >\
              <label for="grpchkall"></label>\
              check all\
            </label>';

      $('body').append(htmlLightbox);
      $( "#surveyDialog1" ).dialog({
          dialogClass:'surveyDialog',             
          width:800,
          height:500,  
          title:'Users who clicked this ad',
            close:function(){
               $(this).dialog("close");
              $("#surveyDialog1" ).remove();
              },
          open:function(){                
              $fluidDialog();
               $("#datacollect").html('');      
               $('#userInfoContainer').append('<div class="loaderOverlay2"></div>'); 
            $.ajax({
              type : "POST",
              dataType : 'json',
              data:{'bannerid':bannerid},
              url : BASE_URL + '/admin/advertisement/showuserlist',        
              success : function(response) {    
                $('.loaderOverlay2').remove();
                $('#surveyDialog1 #userInfoContainer').html(response.content);
                $('#surveyDialog1 #grouplist').html(response.grouplist+checkHtml);                
              }
            });
          }
    });
    
  });
});
</script>
<script> 
           $(document).ready(function() {

            $('body').on('click','.publishAds', function()
            {
               
              msg =' Publishing this banner will Unpublish the current one. Are you sure you want to continue?';             
              var id = $(this).attr('data-id');
              var type = $(this).attr('type-id');
              var status = $(this).attr('status-id');
              var dthis = $(this);
              var globalTab = dthis.closest('table[data-id="globalTab"]');
              if(status=='publish')
              {
                $('#dialogConfirmSetting').remove();
                $('body').append('<div id="dialogConfirmSetting">'+msg+'</div>');

                $( "#dialogConfirmSetting" ).dialog({
                resizable: false,
                title:'Please confirm',
                modal: true,            
                buttons: {
                "Yes": function() {
                $(this).dialog( "close" );
                        $.ajax(
                          {
                              type : "POST",
                              dataType : 'json',
                              data : {'status':status,'advertID':id,'type':type},
                              url : BASE_URL+'/admin/advertisement/publish',
                              beforeSend : function() { 

                              },
                              cache : false,
                              success : function(response) 
                              {               
                                $messageSuccess(response.message);
                               
                                if(status=='publish')
                                {
                                  $('.publishAds', globalTab).html('<i class="fa fa-eye-open"></i>Publish');
                                  $('.publishAds', globalTab).attr('status-id','publish');
                                  $('.publishAds', globalTab).addClass('btn-yellow').removeClass('btn-green');
                                
                                  dthis.html('<i class="fa fa-eye-open"></i>UnPublish');
                                  dthis.attr('status-id','unpublish');
                                  dthis.addClass('btn-green').removeClass('btn-yellow');
                                }
                                else
                                {
                                  dthis.html('<i class="fa fa-eye-open"></i>Publish');
                                  dthis.attr('status-id','publish');
                                  dthis.addClass('btn-yellow').removeClass('btn-green');
                                }
                              },  
                              error : function(error) {

                              }
                          });       
                      }
                    }
                });
              }
              else{
                   $.ajax(
                        {
                            type : "POST",
                            dataType : 'json',
                            data : {'status':status,'advertID':id,'type':type},
                            url : BASE_URL+'/admin/advertisement/publish',
                            beforeSend : function() { 

                            },
                            cache : false,
                            success : function(response) 
                            {               
                              $messageSuccess(response.message);
                              if(status=='publish')
                              {
                                 $('.publishAds', globalTab).html('<i class="fa fa-eye-open"></i>Publish');
                                $('.publishAds', globalTab).attr('status-id','publish');
                                $('.publishAds', globalTab).addClass('btn-yellow').removeClass('btn-green');
                                dthis.html('<i class="fa fa-eye-open"></i>UnPublish');
                                dthis.attr('status-id','unpublish');
                                dthis.addClass('btn-green').removeClass('btn-yellow');
                              }
                              else
                              {
                                dthis.html('<i class="fa fa-eye-open"></i>Publish');
                                dthis.attr('status-id','publish');
                                dthis.addClass('btn-yellow').removeClass('btn-green');
                              }
                            },  
                            error : function(error) {

                            }
                        }); 
              }
            });

            $('body').on('click','.deleteAds', function(){
              var thisEl = $(this);
              var parentTable = $(this).closest('table');
              var id = $(this).attr('data-id');
              msg ='Are you sure you want to delete this advert?';             


              $('#dialogConfirmSetting').remove();
              $('body').append('<div id="dialogConfirmSetting">'+msg+'</div>');

              $( "#dialogConfirmSetting" ).dialog({
                resizable: false,
                title:'Please confirm',
                modal: true,            
                buttons: {
                "Yes": function() {
                    $( this ).dialog( "close" );
                     $.ajax(
                      {
                          type : "POST",
                          dataType : 'json',
                          data : {'advertID':id},
                          url : BASE_URL+'/admin/advertisement/delete',
                          success : function(response) 
                          {               
                           var totalTr =  $('tbody tr', parentTable).size();
                            $('#'+id).remove();
                           if(totalTr==1){
                              parentTable.hide();
                             //window.location.reload();
                           }
                            
                            $messageSuccess(response.message);
                           
                          }
                      });        
                  }
                }
            });
                
                
            });
            
   
            $.cookie("advertID", null, {
                expires : 1,           //expires in 10 days
                path    : '/', 
                domain  : 'db-csp.com',
                secure  : true
            });
   
            $('body').on('click','.SaveOnly', function(){ 
              $('#configuration').ajaxForm(function(response) { 
                  $saveAds(response.advertID);
                });
            });

            $('body').on('click','.SavePreview', function()
            {
                $('#configuration').ajaxForm(function(response) 
                {
                    if(response.status=='success')
                    {
                      $.cookie("advertID", response.advertID, {
                        expires : 1,           //expires in 10 days
                        path    : '/', 
                        domain  : 'db-csp.com',
                        secure  : true
                      });

                      var htmlLightbox = '<div id="detailsDialog"  title="Facebook Friends">\
                      <div id="datacollect" style="float:none"></div>\
                      <div id="userInfoContainer"></div>\
                      </div>';
                      var htmlPreview = '<div class="seeLargeView loader dashBlock">\
                      <h2>\
                      Preview\
                      <a class="closePupPreview pull-right" href="javascript:void(0);">\
                      <i class="fa fa-times"></i>\
                      </a>\
                      <a class="pull-right btn btn-green SavePupPreview" advertID-id="'+response.advertID+'" href="javascript:void(0);" style="margin-right:10px;">Save modification</a>\
                      </h2>\
                      <div><iframe id="previewFrontend" src="'+BASE_URL+'" width="100%" height="100%"></iframe></div></div>';
                      $('.seeLargeView').remove();
                      $('body').append(htmlPreview);
                      $('.overlayPopup').fadeIn();

                       $('#previewFrontend').load(function() {
                           $(this).closest('.seeLargeView').removeClass('loader');
                        });

                        var popHeight = $('.seeLargeView').height();
                        $('.seeLargeView iframe').height(popHeight-50);

                        $('body').on('click','.closePupPreview', function(){
                           $('.overlayPopup, .seeLargeView').fadeOut();
                           $.cookie("advertisement", 'hide', {
                            expires : 1,           //expires in 10 days
                            path    : '/', 
                            domain  : 'db-csp.com',
                            secure  : true
                          });
                       });


                        $('body').on('click','.SavePupPreview', function(){
                            $('.overlayPopup, .seeLargeView').fadeOut();
                            advertID = $(this).attr('advertID-id');
                            $saveAds(advertID);
                        });
                    }else
                      $messageError(response.message);
                });
            });


      var  msgTypeHtml ='';
      var msgType =0;
      var VIP =0;
      var hintText = 'test';
       $('.advWrpMain .dbtab a').bind('click',function(event) {
         $('.createAdvContainer').remove();
         $('.advinnerBtnBar').text('Create Ad');
      });


        $saveAds = function(advertID){
          type = $('#type').val();
          $.ajax({
              type : "POST",
              dataType : 'json',
              url : BASE_URL+'/admin/advertisement/publish',
              cache : false,
              data:{'advertID':advertID,'status':'publish','type':type},
              beforeSend : function() { 
                $.cookie("advertID", null, {
                  expires : 1,           //expires in 10 days
                  path    : '/', 
                  domain  : 'db-csp.com',
                  secure  : false
                });
              },
              success : function(response) {               
                   $messageSuccess(response.message);
                   location.reload();
                  
              }
          });
        }

       $('.advinnerBtnBar').click(function(event) {
            msgType = $('#messageWrapper .dbtab .active a').attr('msgType');
           
            var dataOpenID = $('#messageWrapper .dbtab .active a').attr('href');
     
      if(msgType==2){
         hintText = 'type group name';
         msgTypeHtml ='<div class="formRow grpNameWrapper popTitle">\
                        <label class="label">User Group(s)</label>\
                        <div class="fieldInput field">\
                           <input type="text" id="search" name="search" />\
                        </div>\
                     </div>';
      }else if(msgType==6){ 
         hintText = 'type VIP Group name';
         msgTypeHtml ='<div class="formRow grpNameWrapper popTitle">\
                        <label class="label">VIP user Group(s)</label>\
                        <div class="fieldInput field">\
                           <input type="text" id="search" name="search" />\
                        </div>\
                     </div>';
      }
      else if(msgType==3){
          hintText = 'type user set name';
          msgTypeHtml ='<div class="formRow grpNameWrapper popTitle">\
                             <label class="label">User set(s)</label>\
                              <div class="fieldInput field ">\
                                 <input type="text" id="search" name="search" />\
                              </div>\
                        </div>';
     
      }else if(msgType==4){
         hintText = 'type user name';
         msgTypeHtml ='<div class="formRow popTitle">\
                          <label class="label">User(s)</label>\
                           <div class="fieldInput field ">\
                              <input type="text" id="search" name="search" />\
                           </div>\
                     </div>';
      }
      else if(msgType==5){
         hintText = 'type post title';
         msgTypeHtml ='<div class="formRow popTitle">\
                          <label class="label">Post(s)</label>\
                           <div class="fieldInput field ">\
                              <input type="text" id="search" name="search" />\
                           </div>\
                     </div>';
      }
      else if(msgType==7){
         hintText = 'type event title';
         msgTypeHtml ='<div class="formRow popTitle">\
                          <label class="label">Event(s)</label>\
                           <div class="fieldInput field ">\
                              <input type="text" id="search" name="search" />\
                           </div>\
                     </div>';
      }else{
        hintText = 'test';
        msgTypeHtml = '';
      }

      var creatAdvertisment = '<div class="createAdvContainer">\
      '+msgTypeHtml+'\
      <div class="grpNameWrapper advertismentContentWrp" >\
            <div class="hashUrsrDetails">\
			<div class="formRow">\
                     <label class="label">Ad title</label>\
                     <div class="field">\
                     <input type="hidden" id="type" name="type" value="'+msgType+'" />\
                        <input type="text" name="adstitle" value="" >\
                        <div class="clearfix"></div>\
                     </div>\
                  </div>\
               <h2>\
                  Top banner\
               </h2>\
               <div class="listing">\
                  <div class="formRow">\
                     <label class="label">Select banner images <span class="noteText">(Multiple allowed) <br> <br> <strong>Suggested size</strong> <br>1100px * 130px (Full width) <br> 500px * 95px (Right)  </span><i class="adTips"><a data-id="topBnrAd">Where will this display?</a></i></label>\
                     <div class="field appendType">\
                        <div id="mydeBanner" class="dropzone" >\
                           <div class="fallback">\
                              <input type="file" name="file"  />\
                           </div>\
                        </div>\
                        <div class="headResult"></div>\
                        <div class="clearfix"></div>\
                     </div>\
                  </div>\
                  <div class="formRow">\
                     <label class="label">Position</label>\
                     <div class="field appendType">\
                        <select name="layout" id="layout">\
                           <option value="fullwidth">Full width</option>\
                           <option value="right">Top right corner</option>\
                        </select>\
                     </div>\
                     <div class="clearfix"></div>\
                  </div>\
                  <div class="formRow Tophide">\
                     <label class="label">Display time</label>\
                     <div class="field">\
                        <input type="text" placeholder="No. of seconds" name="headerSpeed" id="headerSpeed" value="" >\
                        <div class="clearfix"></div>\
                     </div>\
                  </div>\
                  <div class="formRow topbannerlink">\
                  </div>\
               </div>\
            </div>\
            <div class="hashUrsrDetails">\
               <h2>\
                  Right side column\
               </h2>\
               <div class="listing">\
                  <div class="formRow">\
                      <label class="label">Select banner images <span class="noteText">(Multiple allowed) <br> <br> <strong>Suggested size</strong> <br> 260px * 206px</span><i class="adTips"><a data-id="rtBnrAd">Where will this display?</a></i></label>\
                     <div class="field appendType">\
                        <div id="myrightBanner" class="dropzone">\
                           <div class="fallback">\
                              <input type="file" name="file"  />\
                           </div>\
                        </div>\
                        <div class="rightResult"></div>\
                        <div class="clearfix"></div>\
                     </div>\
                  </div>\
                  <div class="formRow Righthide">\
                     <label class="label">Create slideshow</label>\
                     <div class="field">\
                        <label for="slideShow" style="display: inline-block; margin-top: 9px;"><input type="checkbox" name="slideShow" id="slideShow" checked value="1"><label for="slideShow">  </label></label>\
                        <div class="clearfix"></div>\
                     </div>\
                  </div>\
                  <div class="formRow Righthide RighthideTime">\
                     <label class="label">Display time</label>\
                     <div class="field">\
                        <input type="text" placeholder="No. of seconds" name="rightSpeed" id="rightSpeed" value="" >\
                        <div class="clearfix"></div>\
                     </div>\
                  </div>\
                  <div class="rightLinkArray">\
                  </div>\
               </div>\
            </div>\
            <div class="formRow" >\
               <div class="field" style="margin-left:0px;">\
                  <button class="btn btn-green SaveOnly" data-id="login">Save</button>\
                  <button class="btn btn-green SavePreview" data-id="login">Preview & save</button>\
                  <span class="noteText" style="margin-left:10px">For preview purposes only the ad will be displayed as a home page preview.</span>\
               </div>\
            </div>\
            </div>\
         </div> <div class="clearfix"> </div>'; 
          if($('.createAdvContainer').is(':visible')==true){
            $('.createAdvContainer').remove();
            $('.advinnerBtnBar').text('Create Ad');
          }else
          {
            $('.advinnerBtnBar', dataOpenID).after(creatAdvertisment);
            $('body').on('click','#slideShow', function(){
                  if(this.checked)
                      $('.RighthideTime').fadeIn('slow');
                  else
                      $('.RighthideTime').fadeOut('slow');
              });
            $('.Righthide').hide();
            $('.Tophide').hide();
            var topimage = 0;
            var rightimage = 0;
            $('.advinnerBtnBar').text('Close');
          }
          $('.advinnerBtnBar').toggleClass('btn-yellow');
            $("#search").tokenInput(BASE_URL+"/admin/getjsonresult?type="+parseInt(msgType),{
               preventDuplicates: true,
               hintText: hintText,
               theme: "facebook",
               resultsLimit: 10,
               resultsFormatter: function(item) 
               {
                    if(msgType==4){
                      return "<li>" + "<img src='" + item.url + "' title='" + item.name + "' height='25px' width='25px' />" + "<div style='display: inline-block; padding-left: 10px;'><div class='full_name'>" + item.name + "</div><div class='email'>" + item.email + "</div></div></li>";
                    }else{
                      return "<li><p>" + item.name + "</p></li>"
                    }
                },
                tokenFormatter: function(item) {
                  if(msgType==4)
                  {
                    return "<li><p><img src='" + item.url + "' title='" + item.name + "' height='25px' width='25px' />" + item.name + "</p></li>"
                  }else{
                      return "<li><p>" + item.name + "</p></li>"
                  }
                }
            });
           
            
               $select('select');

               var myDropzoneBannerval = new Dropzone("#mydeBanner",{
                  url: BASE_URL+'/admin/advertisement/headerbanner',
                  maxFiles: 5,
                  addRemoveLinks: true,
                  uploadMultiple:true,
                  parallelUploads: 1,
                  acceptedFiles: 'image/jpeg,image/png,image/gif',
               });
         
              myDropzoneBannerval.on("error", function (file, serverFileName) {
                  $messageError('Please upload only png, jpg, jpeg, gif file type');
              });
              myDropzoneBannerval.on("maxfilesexceeded", function (file, serverFileName) {
                  $messageError('You can upload only 5 file');
              });     
              myDropzoneBannerval.on("success", function (file, serverFileName) {

                  $('.topbannerlink').append(serverFileName.fileLinkText);
                  $('#saveform').show();
                  topimage = 0;
                  $('.headerImageArray').each(function(){
                    topimage++;
                  });

                  if(topimage<=1)
                    $('.Tophide').hide();
                  else
                    $('.Tophide').show();
              });
              myDropzoneBannerval.on("removedfile", function (file) {
                
                topimage = 0;
                v = $.parseJSON(file.xhr.response);
                $('.headerImageArray').each(function(){ 
                  if(v.filename==$(this).val()){
                    $('div.formRow[data-image="'+v.filename+'"]').remove();
                  }
                });

                $('.headerImageArray').each(function(){
                  topimage++;
                });

                if(topimage<=1)
                  $('.Tophide').hide();
                else
                  $('.Tophide').show();


              });

              var myDropzoneBannerval = new Dropzone("#myrightBanner",{
                  url: BASE_URL+'/admin/advertisement/rightbanner',
                  maxFiles: 5,
                  addRemoveLinks: true,
                  uploadMultiple:true,
                  parallelUploads: 1,
                  acceptedFiles: 'image/jpeg,image/png,image/gif',
               });
         
              myDropzoneBannerval.on("error", function (file, serverFileName) {
                  $messageError('Please upload only png, jpg, jpeg, gif file type');
              });
              myDropzoneBannerval.on("maxfilesexceeded", function (file, serverFileName) {
                  $messageError('You can upload only 5 file');
              });     
              myDropzoneBannerval.on("success", function (file, serverFileName) {
                  $('.rightLinkArray').append(serverFileName.fileLinkText);
                  $('#saveform').show();
                 
                  rightimage = 0;
                  $('.rightImageArray').each(function(){
                    rightimage++;
                  });

                  if(rightimage<=1)
                    $('.Righthide').hide();
                  else{
                    $('.Righthide').show();
                    $("#slideShow").attr('checked', 'checked');

                  }
              });
              myDropzoneBannerval.on("removedfile", function (file) {
                
                rightimage = 0;
                v = $.parseJSON(file.xhr.response);
                $('.rightImageArray').each(function(){ 
                  if(v.filename==$(this).val()){
                    $('div.formRow[data-image="'+v.filename+'"]').remove();
                  }
                });

                $('.rightLinkArray').each(function(){
                  rightimage++;
                });

                if(rightimage<=1)
                  $('.Righthide').hide();
                else
                  $('.Righthide').show();
              });

           });
   }); 
</script> 
<h1 class="pageTitle ">Manage ads<span class="howadswork">How does it work?</span>
<div class="adsnote">Platform advertising works on a priority basis: you can choose where on the platform an ad will appear and who will see it.<br><br><span style="font-weight: bold;">Specific users</span><br>
Advertising for specific user accounts will display on those users’ profile pages, prioritised above any other ads.<br><br>
<span style="font-weight: bold;">Admin user sets</span><br>
Ads selected for display to a larger set of users. If no specific user account ads have been selected, users will see ‘admin user set’-specific ads if one or more has been selected.<br><br>
<span style="font-weight: bold;">Events</span><br>
Event-specific ads will display on all specific event pages and to all users who are ‘attending’.<br><br>
<span style="font-weight: bold;">Specific post and User Groups</span><br>
In each of these cases, ads uploaded to one or more of these will only display on the specific linked pages (ie. on the specific post itself or in the specific Group).  All users that are a part of the specific post or Group will see these ads.<br><br>
<span style="font-weight: bold;">Global ads</span><br>
These ads will display across all other areas of the platform to all users, and this is the default setting for all advertising. If an ad isn’t categorised in one of the options above, it will automatically be categorised as ‘global’.</div>
</h1>
  <div id="messageWrapper" class="dbtabContainer advWrpMain"> 
    <ul class="dbtab">
      <li><a href="#user" rel="user" msgType="4">Specific users</a></li>
      <li><a href="#Usersgroup" rel="Usersgroup" msgType="3">Admin user sets</a></li>
      <li><a href="#event" rel="event" msgType="7">Events</a></li>
      <li><a href="#post" rel="GroupUsers" msgType="5">Specific posts</a></li>
      <li><a href="#PlateformGroup" rel="PlateformGroup" msgType="2">User Groups</a></li>
      <?php
      /*if(clientID!='21' && clientID!='22')
      {
        echo '<li><a href="#PlateformVIPGroup" rel="PlateformGroup" msgType="6">VIP User Groups</a></li>';
      }*/ ?>
      <li class="active"><a href="#allUsers" rel="allUsers" msgType="1">Global</a></li>
    </ul>
      <div class="dbTabContainerDiv">
       <form name="configuration" action ="<?php echo BASE_URL; ?>/admin/advertisement/advertpush" class="right grid" id="configuration" enctype="multipart/form-data" method="post">
            
        <div id="allUsers" class="dbtabContent" style="display:block;">
            <a href="javascript:void(0);" class="advinnerBtnBar btn btn-yellow" >Create ad</a>
             <?php  $result = $this->advert->getAdvert(1); if(!empty($result)){ ?>
             <div class="responsiveTable">
                 <table class="table-border userListTable table table-hover table-stripe " data-id="globalTab">
                     <thead>
                        <tr>
                           <td> Title</td>
                           <td style="width:300px"> Action</td>
                        </tr>
                     </thead>
                     <tbody> 
                      <?php 
                     foreach ($result as $value) {  ?>
                         <tr id="<?php echo $value['id']; ?>" >
                           <td><?php echo $value['advertTitle']; ?></td>
                           <td>
                              <a href="javascript:void('0');" type-id ="<?php echo $value['type']; ?>" status-id ="<?php echo ($value['status']==1) ? 'unpublish':'publish'; ?>" data-id = "<?php echo $value['id']; ?>" class="<?php echo ($value['status']==1) ? 'btn btn-green btn btn-mini publishAds':'btn btn-yellow btn btn-mini publishAds'; ?>"><i class="fa fa-eye-open"></i> <?php echo ($value['status']==1) ? 'UnPublish':'Publish'; ?></a>
                              <a href="<?php echo BASE_URL; ?>/admin/advertisement/edit/id/<?php echo $value['id']; ?>/type/<?php echo $value['type']; ?>" class="btn btn-green btn btn-mini"><i class="fa fa-edit"></i> Edit</a>
                              <a href="javascript:void('0');" data-id = "<?php echo $value['id']; ?>" class="btn btn-danger btn btn-mini deleteAds"><i class="fa fa-times"></i> Delete</a>
                           </td>
                        </tr>
                        <?php } ?>
                     </tbody>
               </table>
             </div>
               <?php }else{ echo '<div class="notfound">No advertisement found </div>'; } ?>
            </div>
        
        <div id="user" class="dbtabContent">
          <a href="javascript:void(0);" class="advinnerBtnBar btn btn-yellow" >Create ad</a>
          <?php  $result = $this->advert->getAdvert(4);
           if(!empty($result)){ ?>
           <div class="responsiveTable">
             <table class="table-border userListTable table table-hover table-stripe">
                     <thead>
                        <tr>
                           <td> Title</td>
                           <td style="width:300px"> Action</td>
                        </tr>
                     </thead>
                     <tbody> 
                       <?php 
                   
                     foreach ($result as $value) {  ?>
                         <tr id="<?php echo $value['id']; ?>" >
                           <td><?php echo $value['advertTitle']; ?></td>
                           <td>
                              <a href="javascript:void('0');" type-id ="<?php echo $value['type']; ?>" status-id ="<?php echo ($value['status']==1) ? 'unpublish':'publish'; ?>" data-id = "<?php echo $value['id']; ?>" class="<?php echo ($value['status']==1) ? 'btn btn-green btn btn-mini publishAds':'btn btn-yellow btn btn-mini publishAds'; ?>"><i class="fa fa-eye-open"></i> <?php echo ($value['status']==1) ? 'UnPublish':'Publish'; ?></a>
                              <a href="<?php echo BASE_URL; ?>/admin/advertisement/edit/id/<?php echo $value['id']; ?>/type/<?php echo $value['type']; ?>" class="btn btn-green btn btn-mini"><i class="fa fa-edit"></i> Edit</a>
                              <a href="javascript:void('0');" data-id = "<?php echo $value['id']; ?>" class="btn btn-danger btn btn-mini deleteAds"><i class="fa fa-times"></i> Delete</a>
                           </td>
                        </tr>
                        <?php } ?>
                     </tbody>
               </table>
             </div>
              <?php }else{ echo '<div class="notfound">No advertisement found </div>'; } ?>
        </div>

        <div id="Usersgroup" class="dbtabContent">
          <a href="javascript:void(0);" class="advinnerBtnBar btn btn-yellow" >Create ad</a>
          <?php $result = $this->advert->getAdvert(3);    if(!empty($result)){ ?>
          <div class="responsiveTable">
             <table class="table-border userListTable table table-hover table-stripe">
                     <thead>
                        <tr>
                           <td> Title</td>
                           <td style="width:300px"> Action</td>
                        </tr>
                     </thead>
                     <tbody> 
                       <?php 
                   
                     foreach ($result as $value) {  ?>
                         <tr id="<?php echo $value['id']; ?>" >
                           <td><?php echo $value['advertTitle']; ?></td>
                           <td>
                              <a href="javascript:void('0');" type-id ="<?php echo $value['type']; ?>" status-id ="<?php echo ($value['status']==1) ? 'unpublish':'publish'; ?>" data-id = "<?php echo $value['id']; ?>" class="<?php echo ($value['status']==1) ? 'btn btn-green btn btn-mini publishAds':'btn btn-yellow btn btn-mini publishAds'; ?>"><i class="fa fa-eye-open"></i> <?php echo ($value['status']==1) ? 'UnPublish':'Publish'; ?></a>
                              <a href="<?php echo BASE_URL; ?>/admin/advertisement/edit/id/<?php echo $value['id']; ?>/type/<?php echo $value['type']; ?>" class="btn btn-green btn btn-mini"><i class="fa fa-edit"></i> Edit</a>
                              <a href="javascript:void('0');" data-id = "<?php echo $value['id']; ?>" class="btn btn-danger btn btn-mini deleteAds"><i class="fa fa-times"></i> Delete</a>
                           </td>
                        </tr>
                        <?php } ?>
                     </tbody>
               </table>
             </div>
             <?php }else{ echo '<div class="notfound">No advertisement found </div>'; } ?>
        </div>

        <div id="PlateformGroup" class="dbtabContent">
          <a href="javascript:void(0);" class="advinnerBtnBar btn btn-yellow" >Create ad</a>
          <?php $result = $this->advert->getAdvert(2); if(!empty($result)){ ?>
          <div class="responsiveTable">
             <table class="table-border userListTable table table-hover table-stripe">
                     <thead>
                        <tr>
                           <td> Title</td>
                           <td style="width:300px"> Action</td>
                        </tr>
                     </thead>
                     <tbody> 
                       <?php 
                   
                     foreach ($result as $value) {  ?>
                         <tr id="<?php echo $value['id']; ?>" >
                           <td><?php echo $value['advertTitle']; ?></td>
                           <td>
                              <a href="javascript:void('0');" type-id ="<?php echo $value['type']; ?>" status-id ="<?php echo ($value['status']==1) ? 'unpublish':'publish'; ?>" data-id = "<?php echo $value['id']; ?>" class="<?php echo ($value['status']==1) ? 'btn btn-green btn btn-mini publishAds':'btn btn-yellow btn btn-mini publishAds'; ?>"><i class="fa fa-eye-open"></i> <?php echo ($value['status']==1) ? 'UnPublish':'Publish'; ?></a>
                              <a href="<?php echo BASE_URL; ?>/admin/advertisement/edit/id/<?php echo $value['id']; ?>/type/<?php echo $value['type']; ?>" class="btn btn-green btn btn-mini"><i class="fa fa-edit"></i> Edit</a>
                              <a href="javascript:void('0');" data-id = "<?php echo $value['id']; ?>" class="btn btn-danger btn btn-mini deleteAds"><i class="fa fa-times"></i> Delete</a>
                           </td>
                        </tr>
                        <?php } ?>
                     </tbody>
               </table>
             </div>
             <?php }else{ echo '<div class="notfound">No advertisement found </div>'; } ?>
        </div>

        <div id="event" class="dbtabContent">
          <a href="javascript:void(0);" class="advinnerBtnBar btn btn-yellow" >Create ad</a>
          <?php $result = $this->advert->getAdvert(7);    if(!empty($result)){ ?>
            <div class="responsiveTable">
             <table class="table-border userListTable table table-hover table-stripe">
                     <thead>
                        <tr>
                           <td> Title</td>
                           <td style="width:300px"> Action</td>
                        </tr>
                     </thead>
                     <tbody> 
                       <?php 
                   
                     foreach ($result as $value) {  ?>
                         <tr id="<?php echo $value['id']; ?>" >
                           <td><?php echo $value['advertTitle']; ?></td>
                           <td>
                              <a href="javascript:void('0');" type-id ="<?php echo $value['type']; ?>" status-id ="<?php echo ($value['status']==1) ? 'unpublish':'publish'; ?>" data-id = "<?php echo $value['id']; ?>" class="<?php echo ($value['status']==1) ? 'btn btn-green btn btn-mini publishAds':'btn btn-yellow btn btn-mini publishAds'; ?>"><i class="fa fa-eye-open"></i> <?php echo ($value['status']==1) ? 'UnPublish':'Publish'; ?></a>
                              <a href="<?php echo BASE_URL; ?>/admin/advertisement/edit/id/<?php echo $value['id']; ?>/type/<?php echo $value['type']; ?>" class="btn btn-green btn btn-mini"><i class="fa fa-edit"></i> Edit</a>
                              <a href="javascript:void('0');" data-id = "<?php echo $value['id']; ?>" class="btn btn-danger btn btn-mini deleteAds"><i class="fa fa-times"></i> Delete</a>
                           </td>
                        </tr>
                        <?php } ?>
                     </tbody>
               </table>
             </div>
             <?php }else{ echo '<div class="notfound">No advertisement found </div>'; } ?>
        </div>

        <div id="PlateformVIPGroup" class="dbtabContent">
          <a href="javascript:void(0);" class="advinnerBtnBar btn btn-yellow" >Create ad</a>
          <?php $result = $this->advert->getAdvert(6); if(!empty($result)){ ?>
            <div class="responsiveTable">
             <table class="table-border userListTable table table-hover table-stripe">
                     <thead>
                        <tr>
                           <td> Title</td>
                           <td style="width:300px"> Action</td>
                        </tr>
                     </thead>
                     <tbody> 
                       <?php
                     foreach ($result as $value) {  ?>
                         <tr id="<?php echo $value['id']; ?>" >
                           <td><?php echo $value['advertTitle']; ?></td>
                           <td>
                              <a href="javascript:void('0');" type-id ="<?php echo $value['type']; ?>" status-id ="<?php echo ($value['status']==1) ? 'unpublish':'publish'; ?>" data-id = "<?php echo $value['id']; ?>" class="<?php echo ($value['status']==1) ? 'btn btn-green btn btn-mini publishAds':'btn btn-yellow btn btn-mini publishAds'; ?>"><i class="fa fa-eye-open"></i> <?php echo ($value['status']==1) ? 'UnPublish':'Publish'; ?></a>
                              <a href="<?php echo BASE_URL; ?>/admin/advertisement/edit/id/<?php echo $value['id']; ?>/type/<?php echo $value['type']; ?>" class="btn btn-green btn btn-mini"><i class="fa fa-edit"></i> Edit</a>
                              <a href="javascript:void('0');" data-id = "<?php echo $value['id']; ?>" class="btn btn-danger btn btn-mini deleteAds"><i class="fa fa-times"></i> Delete</a>
                           </td>
                        </tr>
                        <?php } ?>
                     </tbody>
               </table>
             </div>
             <?php }else{ echo '<div class="notfound">No advertisement found </div>'; } ?>
        </div>


        <div id="post"class="dbtabContent">
          <a href="javascript:void(0);" class="advinnerBtnBar btn btn-yellow" >Create ad</a>

              <?php  
                      $result = $this->advert->getAdvert(5); if(!empty($result)){ ?>
                      <div class="responsiveTable">
               <table class="table-border userListTable table table-hover table-stripe">
                     <thead>
                        <tr>
                           <td> Title</td>
                           <td style="width:300px"> Action</td>
                        </tr>
                     </thead>
                     <tbody> 
                       <?php 
                    
                     foreach ($result as $value) {  ?>
                         <tr id="<?php echo $value['id']; ?>" >
                           <td><?php echo $value['advertTitle']; ?></td>
                           <td>
                              <a href="javascript:void('0');" type-id ="<?php echo $value['type']; ?>" status-id ="<?php echo ($value['status']==1) ? 'unpublish':'publish'; ?>" data-id = "<?php echo $value['id']; ?>" class="<?php echo ($value['status']==1) ? 'btn btn-green btn btn-mini publishAds':'btn btn-yellow btn btn-mini publishAds'; ?>" ><i class="fa fa-eye-open"></i> <?php echo ($value['status']==1) ? 'UnPublish':'Publish'; ?></a>
                              <a href="<?php echo BASE_URL; ?>/admin/advertisement/edit/id/<?php echo $value['id']; ?>/type/<?php echo $value['type']; ?>" class="btn btn-green btn btn-mini"><i class="fa fa-edit"></i> Edit</a>
                              <a href="javascript:void('0');" data-id = "<?php echo $value['id']; ?>" class="btn btn-danger btn btn-mini deleteAds"><i class="fa fa-times"></i> Delete</a>
                           </td>
                        </tr>
                        <?php } ?>
                     </tbody>
               </table>
             </div>
               <?php }else{ echo '<div class="notfound">No advertisement found </div>'; } ?>
        </div>
      </form>
      </div>
  </div>
  

<div class="tipBnrImg" id="dialogTopBnr"><img src="<?php echo BASE_URL; ?>/img/top-bnner.png"/></div>
<div class="tipBnrImg" id="dialogRtBnr"><img src="<?php echo BASE_URL; ?>/img/right-bnner.png"/></div>