<?php         
$this->title = "Scoring & leagues";
$this->headTitle($this->title);
$common    = new Admin_Model_Common(); 

$Groupdropdown = $common->Groupdropdown(); 
  $groupFound='block';
  if(empty($Groupdropdown)){
    $notfound = '<div class="noFound">No groups found</div>';
    $groupFound='none';
  }
if($this->searchuser != "") 
{
  $searchuser = $this->searchuser;
}else
{
  $searchuser = '';
}
?>

<h1 class="pageTitle " id="main">Scoring</h1>
<?php 
if($searchuser != "") {
  ?>
<div style="margin-bottom:20px;font-size:16px; font-weight:bold">Search keyword: "<?php echo $searchuser; ?>"  <a class="btn btn-mini" style="margin-left:10px;" title="Refresh" href="">Reset</a></div>
<?php } ?>

<div class="clearfix"></div>

<div class="postDataScoreSearchWrp">
	 
	<?php 

  if($this->totalpostinf > 0 || $this->totalgrpinf > 0 || $this->totaleventinf > 0) { ?>
		 <form name="scoreposttype" id="scoreposttype" action="<?php echo $this->url(array('controller'=>'leaguescore','action'=>'index'));?>" method="POST"  class="pull-left ">
			<select class="gh-tb select2 pull-left"  maxlength="350" value="" id="posttype" name="posttype" onchange="ScoreTypeFilter2(this.value);" > 
				<option value="" selected="selected"> - Select scoring source - </option>				
        <?php if($this->totalpostinf > 0) { ?>
        <option value="0" <?php if($this->type==0){ echo"selected=selected"; } ?>> Posts </option>
        <?php } ?>
        <?php if($this->totalgrpinf > 0) { ?>
        <option value="1" <?php if($this->type==1){ echo"selected=selected"; } ?>> Groups</option>
        <?php } ?>
        <?php if($this->totaleventinf > 0) { ?>
        <option value="2" <?php if($this->type==2){ echo"selected=selected"; } ?>> Events</option>
        <?php } ?>
			</select>
				
	 <!-- </form>    -->
  <?php } ?>
  

	 <div id="formComment" class="pull-left"> 
   <?php
    if($this->influencecomment!="")
    {
        $postid=$this->influencecomment;
    }else
    {
       $postid='';
    }
   
    if(count($this->result) >0 && $this->type!=5) {
    ?>	   
   <select name="influencecomment" id="postDataScore" class="gh-tb pull-left select2" >
    <option value="">All</option>
    <?php
   

   
        foreach ($this->result as $key => $value) 
         {
          ?>
        <option value="<?=$value['id']?>" <?php if($postid==$value['id']){ echo"selected=selected"; } ?>><?=$value['text']?></option>   
        <?php                
         }
      
     ?>
     </select>
     <?php } ?>  
   </div>
     <?php


      if($postid!="" || $this->type!=5) {?>
     <a class="btn btn-mini" style="margin-left:10px;" title="Refresh" href="<?php echo BASE_URL ?>/admin/leaguescore/">Reset</a>
     <?php } 
      if($this->totalpostinf > 0 || $this->totalgrpinf > 0 || $this->totaleventinf > 0) { ?>
   </form>
   <?php } ?>
</div>
<input type="hidden" value="scoringandleagues" name="action2" id="action2">

<div id="messageWrapper" class="dbtabContainer advWrpMain" data-type="table"> 
    <ul class="dbtab">
       <li class="active"><a href="#like" rel="like">Like</a></li>
       <li><a href="#love" rel="PlateformGroup" >Love</a></li>
       <li><a href="#dislike" rel="PlateformGroup" >Dislike</a></li>
       <li><a href="#sad" rel="PlateformGroup" >Sad</a></li> 
      
       <div class="grpTopTabel "> 
         <form action="<?php echo $this->url(array('controller'=>'leaguescore','action'=>'index'));?>" method="POST" name="frm"  class="pull-left select2DropDown">
          <input type="hidden" name="type" value="<?=$this->type?>">
          <input type="hidden" name="influencecomment" value="<?=$postid?>">
          <input type="text" name="searchuser" id="searchuser" style="margin-right:10px; line-height:16px;" value="<?=$searchuser?>" data-order="searchuser" placeholder="type name to search" >          
         </form>
        <?php echo $grouplist = $common->addtogroupbutton(); ?>
      </div>     
    </ul>

  
  
<div id="like" class="dbtabContent" style="display:block;">
  <div class="jointElement" style="font-size: 14px; margin-left: 0; margin-top: 15px;">
    <ul>
      <li class="active"><a href="javascript:void(0);" class="orderscore" data-score="2" data-order="received">Received</a></li>
      <li><a href="javascript:void(0);" class="orderscore" data-score="2" data-order="given">Given</a></li>
    </ul>
 </div>
<div class="responsiveTable">
<table class="reportingTable table-border userListTable table table-hover table-stripe" id="tab1">
<thead>
	<?php  if (count($this->paginator)){ ?>
	<?php $rowchange	=	0; 
	?>	
	<tr>
      <td width="16">
          <label title="Select all" for="tlallresult">
            <input type="checkbox" name="goupusermain" id="tlallresult" class="goupusermain" value="allInResults" />
            <label for="tlallresult"></label>
          </label> 
      </td>
	    <td width="250">
        Name       
      </td>

	   <!--  <td width="260">Very positive scores <br><span style="font-weight:normal; font-size: 13px;">(A 'strongly agree' score = 3 'agree' scores)</span></td>
	    <td width="250">Positive scores</td> -->
	    <td width="250">Total score </td>	 
	</tr>
</thead>
<tbody id="likebody">
<?php foreach($this->paginator as $user) : ?>
<?php if($rowchange%2==1) {$color = '#CCC';} else {$color ='#FFF';} ?>

<tr id="<?php echo $user['total'];?>">
    <td>
      <label>
        <input class="goupuser" type="checkbox" value="<?php echo $user['UserID'];?>" name="goupuserid" id="goupuserid<?php echo $user['UserID'];?>">
        <label></label>
      </label>
    </td>
    <td >
      <div class="usImg">
    	 <img class="imgStyle" src="<?php echo IMGPATH ?>/users/small/<?php echo $user['ProfilePic']; ?>" width="40" height="40">
        </div>         
         <div class="udetailtop">
          <div class="oneline">
    	       <?php echo $this->myclientdetails->customDecoding($this->escape($user['Name'])).' '.$this->myclientdetails->customDecoding($this->escape($user['lname']));?>     
       </div>
      </div>    
    </td>
       
   
    <!-- <td><?php echo $user['likes'];?></td>
    <td><?php echo $user['love'];?></td> -->	
    <td><strong><?php echo $user['total'];?></strong></td>    
</tr>
<?php endforeach; ?>
<?php } else { ?>
	<tr><td colspan="4"><!-- <a href="<?php echo BASE_URL ?>/admin/influence" class="btn btn-black pull-left">Back to main list</a> --></td></tr>	
	<tr><td colspan="4"><div class="notfound">No results <input type="hidden" id="postnotfound" value="0"></div></td></tr>	
	<?php } ?>

</tbody>
</table>
</div>
<?php  if (count($this->countrow) > 20){ ?>
<div id="results"></div>
<div align="center">
  <button class="load_more btn btn-large btn-full" data-type="love" id="load_more_button">More</button>
  <div class="animation_image" style="display:none;"><img src="<?php echo BASE_URL ?>/images/loader2.gif"> Loading...</div>
</div>
<?php } ?>




</div>


 <div id="love" class="dbtabContent">
 <div class="jointElement" style="font-size: 14px; margin-left: 0; margin-top: 15px;">
    <ul>
      <li class="active"><a href="javascript:void(0);" class="orderscore" data-score="1" data-order="received">Received</a></li>
      <li><a href="javascript:void(0);" class="orderscore" data-score="1" data-order="given">Given</a></li>
    </ul>
 </div>
<div class="responsiveTable">
<table class="reportingTable table-border userListTable table table-hover table-stripe" id="tab2">
<thead>
	<?php  if (count($this->paginator2)){ ?>
	<?php $rowchange	=	0; 
	?>	
	<tr>
      <td width="16">
          <label title="Select all" for="negativeAllresult">
            <input type="checkbox" name="goupusermain" id="negativeAllresult" class="goupusermain" value="allInResults" />
            <label for="negativeAllresult"></label>
          </label> 
      </td>
	    <td width="250">
        Name 
			</div>
		</td>
	   <!--  <td width="260" nowrap="nowrap">Very negative scores <br><span style="font-weight:normal; font-size: 13px;">(A 'strongly disagree' score = 3 'disagree' scores)</span></td>
	    <td width="250">Negative scores</td> -->
	    <td width="250">Total score </td>	 
	</tr>
</thead>
<tbody id="lovebody">
<?php foreach($this->paginator2 as $user) : ?>
<?php if($rowchange%2==1) {$color = '#CCC';} else {$color ='#FFF';} ?>
<?php //print_r($user); die; ?>
<tr id="<?php echo $user['total'];?>">
    <td>
        <label>
          <input class="goupuser" type="checkbox" value="<?php echo $user['UserID'];?>" name="goupuserid" id="goupuserid<?php echo $user['UserID'];?>">
          <label></label>
        </label>
    </td>
    <td >
        <div class="usImg">
      	 <img class="imgStyle" src="<?php echo IMGPATH ?>/users/small/<?php echo $user['ProfilePic']; ?>" width="40" height="40"></div>
         
         <div class="udetailtop">
          <div class="oneline">
      	<?php echo $this->myclientdetails->customDecoding($this->escape($user['Name'])).' '.$this->myclientdetails->customDecoding($this->escape($user['lname']));
       

        ?>
        </div>
      </div>
    </td>
    <!--  <td><?php echo $user['hate'];?></td> 
    <td><?php echo $user['dislike'];?></td>   --> 
    <td><strong><?php echo $user['total'];?></strong></td>
    
</tr>

<?php endforeach; ?>
<?php } else { ?>
	<tr><td colspan="4"><!-- <a href="<?php echo BASE_URL ?>/admin/influence" class="btn btn-black pull-left">Back to main list</a> --></td></tr>	
	<tr><td colspan="4"><div class="notfound">No results <input type="hidden" id="postnotfound" value="0"></div></td></tr>	
	<?php } ?>

</tbody>
</table>
</div>

  <div id="results2"></div>
  <?php  if (count($this->countrow2) > 20){ ?>
    <div align="center">
      <button class="load_more btn btn-large btn-full" id="load_more_button" data-type="hate">More</button>
      <div class="animation_image" style="display:none;"><img src="<?php echo BASE_URL ?>/images/loader2.gif"> Loading...</div>
    </div>
<?php } ?>
</div>


<div id="dislike" class="dbtabContent">
  <div class="jointElement" style="font-size: 14px; margin-left: 0; margin-top: 15px;">
    <ul>
      <li class="active"><a href="javascript:void(0);" class="orderscore" data-score="4" data-order="received">Received</a></li>
      <li><a href="javascript:void(0);" class="orderscore" data-score="4" data-order="given">Given</a></li>
    </ul>
 </div>

<div class="responsiveTable">
<table class="reportingTable table-border userListTable table table-hover table-stripe" id="tab2">
<thead>
  <?php  if (count($this->paginator2)){ ?>
  <?php $rowchange  = 0; 
  ?>  
  <tr>
      <td width="16">
          <label title="Select all" for="negativeAllresult">
            <input type="checkbox" name="goupusermain" id="negativeAllresult" class="goupusermain" value="allInResults" />
            <label for="negativeAllresult"></label>
          </label> 
      </td>
      <td width="250">
         Name 
      </div>
    </td>
      <!-- <td width="260" nowrap="nowrap">Very negative scores <br><span style="font-weight:normal; font-size: 13px;">(A 'strongly disagree' score = 3 'disagree' scores)</span></td>
      <td width="250">Negative scores</td> -->
      <td width="250">Total score </td>  
  </tr>
</thead>
<tbody id="dislikebody">
<?php foreach($this->paginator3 as $user) : ?>
<?php if($rowchange%2==1) {$color = '#CCC';} else {$color ='#FFF';} ?>
<?php //print_r($user); die; ?>
<tr id="<?php echo $user['total'];?>">
    <td>
        <label>
          <input class="goupuser" type="checkbox" value="<?php echo $user['UserID'];?>" name="goupuserid" id="goupuserid<?php echo $user['UserID'];?>">
          <label></label>
        </label>
    </td>
    <td >
        <div class="usImg">
         <img class="imgStyle" src="<?php echo IMGPATH ?>/users/small/<?php echo $user['ProfilePic']; ?>" width="40" height="40"></div>
         
         <div class="udetailtop">
          <div class="oneline">
        <?php echo $this->myclientdetails->customDecoding($this->escape($user['Name'])).' '.$this->myclientdetails->customDecoding($this->escape($user['lname']));       


        ?>
        </div>
      </div>
    </td>
    <!--  <td><?php echo $user['hate'];?></td> 
    <td><?php echo $user['dislike'];?></td>   --> 
    <td><strong><?php echo $user['total'];?></strong></td>
    
</tr>

<?php endforeach; ?>
<?php } else { ?>
  <tr><td colspan="4"><!-- <a href="<?php echo BASE_URL ?>/admin/influence" class="btn btn-black pull-left">Back to main list</a> --></td></tr> 
  <tr><td colspan="4"><div class="notfound">No results <input type="hidden" id="postnotfound" value="0"></div></td></tr>  
  <?php } ?>

</tbody>
</table>
</div>

  <div id="results2"></div>
  <?php  if (count($this->countrow3) > 20){ ?>
    <div align="center">
      <button class="load_more btn btn-large btn-full" id="load_more_button" data-type="hate">More</button>
      <div class="animation_image" style="display:none;"><img src="<?php echo BASE_URL ?>/images/loader2.gif"> Loading...</div>
    </div>
<?php } ?>
</div>



<div id="sad" class="dbtabContent">
<div class="jointElement" style="font-size: 14px; margin-left: 0; margin-top: 15px;">
    <ul>
      <li class="active"><a href="javascript:void(0);" class="orderscore" data-score="5" data-order="received">Received</a></li>
      <li><a href="javascript:void(0);" class="orderscore" data-score="5" data-order="given">Given</a></li>
    </ul>
 </div>
<div class="responsiveTable">
<table class="reportingTable table-border userListTable table table-hover table-stripe" id="tab2">
<thead>
  <?php  if (count($this->paginator4)){ ?>
  <?php $rowchange  = 0; 
  ?>  
  <tr>
      <td width="16">
          <label title="Select all" for="negativeAllresult">
            <input type="checkbox" name="goupusermain" id="negativeAllresult" class="goupusermain" value="allInResults" />
            <label for="negativeAllresult"></label>
          </label> 
      </td>
      <td width="250">
              Name 
    </td>
      <!-- <td width="260" nowrap="nowrap">Very negative scores <br><span style="font-weight:normal; font-size: 13px;">(A 'strongly disagree' score = 3 'disagree' scores)</span></td>
      <td width="250">Negative scores</td> -->
      <td width="250">Total score </td>  
  </tr>
</thead>
<tbody id="sadbody">
<?php foreach($this->paginator4 as $user) : ?>
<?php if($rowchange%2==1) {$color = '#CCC';} else {$color ='#FFF';} ?>
<?php //print_r($user); die; ?>
<tr id="<?php echo $user['total'];?>">
    <td>
        <label>
          <input class="goupuser" type="checkbox" value="<?php echo $user['UserID'];?>" name="goupuserid" id="goupuserid<?php echo $user['UserID'];?>">
          <label></label>
        </label>
    </td>
    <td >
        <div class="usImg">
         <img class="imgStyle" src="<?php echo IMGPATH ?>/users/small/<?php echo $user['ProfilePic']; ?>" width="40" height="40"></div>
         
         <div class="udetailtop">
          <div class="oneline">
        <?php echo $this->myclientdetails->customDecoding($this->escape($user['Name'])).' '.$this->myclientdetails->customDecoding($this->escape($user['lname']));
       


        ?>
        </div>
      </div>
    </td>
    <!--  <td><?php echo $user['hate'];?></td> 
    <td><?php echo $user['dislike'];?></td>   --> 
    <td><strong><?php echo $user['total'];?></strong></td>
    
</tr>

<?php endforeach; ?>
<?php } else { ?>
  <tr><td colspan="4"><!-- <a href="<?php echo BASE_URL ?>/admin/influence" class="btn btn-black pull-left">Back to main list</a> --></td></tr> 
  <tr><td colspan="4"><div class="notfound">No results <input type="hidden" id="postnotfound" value="0"></div></td></tr>  
  <?php } ?>

</tbody>
</table>
</div>

  <div id="results2"></div>
  <?php  if (count($this->countrow4) > 20){ ?>
    <div align="center">
      <button class="load_more btn btn-large btn-full" id="load_more_button" data-type="hate">More</button>
      <div class="animation_image" style="display:none;"><img src="<?php echo BASE_URL ?>/images/loader2.gif"> Loading...</div>
    </div>

<?php } ?>

<script type="text/javascript">
	$(function(){
		$('#posttype, #postDataScore').select2({width:350});

      $('body').on('click','.dbtab > li a',function(){
          var tab = $(this).attr('href');
         checkDataReport(tab);
      });

      $('.dbtab li.active a').trigger('click');
      $('#searchuser').keypress(function(e){
        var keycode = (e.keyCode ? e.keyCode : e.which);
          if(keycode==13){
             var searchuserval = $('#searchuser').val();
             document.frm.submit();
            //$('.orderscore:visible:first').trigger('click',searchuserval,[searchuserval]);
          }
      });

      $("#postDataScore").change(function() {        
           document.scoreposttype.submit();
      });
       

      $('body').on('click','.orderscore',function(e,param1){

      var thisEl     =  $(this);
      var datascore  = $(this).attr('data-score');
      var dataorder  = $(this).attr('data-order');
      var parentEl   = thisEl.closest('.dbtabContent');
      var searchval  = '<?=$searchuser?>';
      var comentid=$('#postDataScore').val();
      var posttype=$('#posttype').val();

      

     
      
      url     =   BASE_URL+"/admin/leaguescore/scoregiven";
      thisEl.closest('ul').find('.active').removeClass('active');
      thisEl.closest('li').addClass('active');
      $.ajax({                                      
      url: url,                  //the script to call to get data          
      data: {'score':datascore,'order':dataorder,'searchval':searchval,'influencecomment':comentid,'type':posttype},                        //you can insert url argumnets here to pass to api.php
      type:'post',
      dataType: 'json', 
      beforeSend:function(){
       
        $('i', thisEl).remove();
        thisEl.append('<i class="fa fa-spin fa-spinner"></i>');                         
      },   //data format    
      success: function(data)  //on recieve of reply
      {   
          $('i', thisEl).remove();
          if(data.content!="")
          {         
            $('tbody', parentEl).html(data.content);
          //  $('#totalinfluence', parentEl).html(data.total);
             $(".load_more").show();
            
          }       
  
      }
      });
    }) //end function



	});       


$(".load_more").click(function (e) { //user clicks on button    
        var thisEl     =  $(this);
       
        var dataorder  = $(this).attr('data-order');
        var parentEl   = thisEl.closest('.dbtabContent');
        var datascore  = $('.jointElement li.active a', parentEl).attr('data-score');     
        var searchval = '<?=$searchuser?>';
        

       
      	   	
      	var URL = BASE_URL+'/admin/leaguescore/scoregiven';
      	
      	  var parentEl = thisEl.closest('.dbtabContent');
        	var lastId = parentEl.find('table tbody tr:last').attr('id');
        	var comentid=$('#postDataScore').val();
          var posttype=$('#posttype').val();

           		var thisFormValue = $(this).closest('form').serializeArray();
                 $.ajax({                                      
                        url: URL,
                        type : "POST",
                         dataType:'json',
                         data:{'lastId':lastId,'score':datascore,'order':dataorder,'searchval':searchval,'influencecomment':comentid,'type':posttype},
                         beforeSend:function(){
                         	$('i', thisEl).remove();
                         	thisEl.append('<i class="fa fa-spin fa-spinner"></i>');
                         },
                        success: function(data){
                        	$('i', thisEl).remove();
                          if(data.content!="")
                          {                          
                            $('tbody', parentEl).append(data.content);
                          //  $('#totalinfluence', parentEl).html(data.total);
                             if(data.total > 0)
                             {
                               thisEl.show();
                             }
                             else
                             {
                              thisEl.hide();
                             }
                            
                          }                         
                          
                        }
                    });          
        });

</script>