<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

<title>Untitled Document</title>

<? //include 'head.php'; ?>

<script src="http://code.jquery.com/jquery-latest.js"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.0/jquery.min.js"></script>

<script>

$(function() {

	setTimeout("parent.Shadowbox.close()",3000);

});

</script>



<style type="text/css">

<!--

.style3 {	font-size: 12px;

	font-weight: bold;

}

body {

	margin-left: 0px;

	margin-top: 0px;

	margin-right: 0px;

	margin-bottom: 0px;

	background-color: #FFFFFF;

}

-->

</style>


</head>



<body>

<div id="signuplastWrapper">

  <div class="user-name" align="center" style="padding:10px; float:none; padding-top:120px; color:#999999">Abuse report sent to admin.</div>

</div>

</body>

</html>

