<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => 'http://dbee.me/images/favicon.png'))

                        ->prependStylesheet(BASE_URL . '/css/style.css')                                  

						->prependStylesheet(BASE_URL . '/css/styles.css')											

						->prependStylesheet(BASE_URL . '/css/jquery.css')

									

?>

<!-- Scripts -->

<?php echo $this->headScript()->prependFile(BASE_URL . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))

                     // ->prependFile(BASE_URL . '/js/bootstrap.min.js')

					  ->prependFile(BASE_URL . '/js/smooth.pack.js')

                      ->prependFile(BASE_URL . '/js/jquery.min.js')

				      ->prependFile(BASE_URL . '/js/functions.js')

				      ->prependFile(BASE_URL . '/js/browser_check.js')				      

				      ->prependFile(BASE_URL . '/js/jquery-latest.js')

				      ->prependFile(BASE_URL . '/js/jquery.min_1.4.4.js')

				      ->prependFile(BASE_URL . '/js/jquery.min_1.4.js')

				      ->prependFile(BASE_URL . '/js/jquery.slideto.v1.1.js')					    	      

				      ->prependFile(BASE_URL . '/js/javascript.js')				    

				      ->prependFile(BASE_URL . '/js/jquery.js')

				    				   

 ?>

<script src="http://code.jquery.com/jquery-latest.js"></script>

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.0/jquery.min.js"></script>	

<style type="text/css">

body {background-color:#FFFFFF}

</style>


<div id="signuplastWrapper">

  <div class="user-name" style="padding:10px;">Found a bug? Report it here</div>

	<div class="next-line"></div>

  <div style="padding:10px; width:auto;">

  	<div id="bugform">

		<div style="float:left; width:80px; font-size:12px">Bug details</div>

		<div style="float:left; margin-bottom:10px"><textarea id="bug" class="roundedge-textbox fieldtext" style="height:150px; width:300px;"></textarea></div>

		<div class="next-line"></div>

		<div style="margin-bottom:10px; float:left; width:80px; font-size:12px">Your browser</div>

		<div style="float:left">

		<select id="userbrowser" class="roundedge-textbox fieldtext">

			<option value="0">Select your browser</option>

			<option value="Internet Explorer">Internet Explorer</option>

			<option value="Mozilla Firefox">Mozilla Firefox</option>

			<option value="Google Chrome">Google Chrome</option>

			<option value="Safari">Safari</option>

		</select>

		</div>

		<div class="next-line"></div>

		<div class="button" style="margin:10px 0 0 80px; float:right" onclick="javascript:sendbugreport()">send</div>

	</div>

	<div id="bugreport-message" style="padding:10px; margin-top:5px; font-size:14px; font-weight:bold; color:#999999;"></div>

</div>

</div>