<link href="<?php echo BASE_URL;?>/css/styles.css" media="screen" rel="stylesheet" type="text/css" />


<div style="height:320px">



<?php



$NameRow = $this->user;



$UserName=ucwords($NameRow['Name']).' is';

$UserNamemsg=ucwords($NameRow['Name']);


echo '<div id="my-dbees" style="padding: 10px 10px 10px 10px;"><div class="user-name" style="margin-bottom:15px">'.$UserName.' following</div><div class="next-line"></div><div>';     

 

echo '<div id="mydbcontrols"></div>';



if(count($this->followingdbees)>0) {

	$counter=1;

	foreach($this->followingdbees as $Row):

		$return.='<a href="/user/'.$Row['Username'].'" target="_top"><div class="follower-box-auto"><img src="'.BASE_URL_IMAGES.'/show_thumbnails.php?ImgName='.$Row['ProfilePic'].'&ImgLoc=userpics&Width=95&Height=95" border="0" /><br /><div style="width:95px">'.$Row['Name'].'</div></div></a>';

		if($counter%5==0) $return.='<div class="next-line"></div>';

		$counter++;

	endforeach;

}

else {

	//$return.=$UserName.' currently not following anyone.';

	$return.='<div class="noFound" align="center" style="margin-top:50px;">'.$UserNamemsg.' is currently not following anyone.</div>';

}

$return.='<br style="clear:both; font-zise:1px" /></div></div>';



echo $return;





?>

</div>