<!DOCTYPE html>
<html  xmlns:fb="http://ogp.me/ns/fb#" class="">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta charset="utf-8">
<meta name="google-site-verification" content="bkNSThfGq7bst2kv6fOSofS4yM8HVQpDf_uj7T2NJaM" />
<?php 

$myclientdetails = new Application_Model_Clientdetails();
$dbeecontrollers = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();
$dbeecontrollersaction = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
$checkImage = new Application_Model_Commonfunctionality();

if($dbeecontrollers == 'dbeedetail' && $dbeecontrollersaction == 'home' )
{
	if(count($this->dbright)>0)
	{
		$dbdetail_obj= $this->dbright;
		// check db in league

		$leagueObj 	=	new Application_Model_League();
		$dbinleague 	=	$leagueObj->chkdbinleague($dbdetail_obj['DbeeID']);
		$dbtittle = htmlspecialchars_decode($this->escape($dbdetail_obj['Text'])); 
		if($dbdetail_obj['Type']==1){
			$dbdiscription = htmlspecialchars_decode($this->escape($dbdetail_obj['Text']));
		}
		else if($dbdetail_obj['Type']==2){
			
			$dbdiscription = htmlspecialchars_decode($this->escape($dbdetail_obj['LinkDesc']));
			$userprofileLinkPic = $checkImage->checkImgExist($dbdetail_obj['LinkPic'],'imageposts','default-avatar.jpg');
			$image = IMGPATH.'/imageposts/medium/'.$userprofileLinkPic.'';
		}
		else if($dbdetail_obj['Type']==3){
			
			$dbdiscription = htmlspecialchars_decode($this->escape($dbdetail_obj['PicDesc']));
			$userprofilePic = $checkImage->checkImgExist($dbdetail_obj['Pic'],'imageposts','default-avatar.jpg');
			$image = IMGPATH.'/imageposts/'.$userprofilePic.'';
		}
		else if($dbdetail_obj['Type']==4){
			
			$dbdiscription = htmlspecialchars_decode($this->escape($dbdetail_obj['VidDesc']));
			$image = 'http://i.ytimg.com/vi/'.$dbdetail_obj['VidID'].'/0.jpg';
		}
		else if($dbdetail_obj['Type']==5){
			//$dbtittle = $dbdetail_obj['PollText']; 
			$dbdiscription = htmlspecialchars_decode($this->escape($dbdetail_obj['PollText']));
			$image = htmlentities($dbdetail_obj['PollText']);
		}
		$url = URL.'/dbeedetail/home/id/'.$dbdetail_obj['DbeeID'];

	}	
	$url = (empty($url)) ? 'https://db-csp.com' : $url;
	
	$dbtittle = (empty($dbtittle)) ? $this->getSeoConfiguration->SiteTitle : $dbtittle;
	$dbdiscription = $this->getSeoConfiguration->SiteDescription;

	
	if($this->configuration->SiteLogo!='')
		$image = URL.'/img/'.$this->configuration->SiteLogo;
	
	$dbtittle  = strip_tags($dbtittle);
	echo '<meta property="og:url" content="'.$url.'" />
	<meta property="og:type" content="article" />
	<meta property="og:title" content="'.utf8_encode(substr($dbtittle,0,70)).'" />
	<meta property="og:site_name" content="db" />
	<meta property="og:description" content="'.$dbdiscription.'" />
	<meta property="og:image" content="'.$image.'" />';
	echo '<title>'.substr(strip_tags($dbtittle),0,70).'</title>';
}
else if($dbeecontrollers == 'group')
{
	$MyGroup = $this->session_name_space->row[0];
	
    $groupimg = $checkImage->checkImgExist($MyGroup['GroupPic'],'grouppics','default-avatar.jpg');

	$url = BASE_URL . '/group/groupdetails/group/' . $MyGroup['ID'];
	$dbtittle = ($MyGroup['GroupName']=='') ? $this->getSeoConfiguration->SiteTitle : $MyGroup['GroupName'];
	$dbdiscription = ($MyGroup['GroupDesc']=='') ? $this->getSeoConfiguration->SiteDescription : $MyGroup['GroupDesc'];
	$dbtittle = strip_tags($dbtittle);

	if($this->SocialLogo!='')
		$image = URL.'/img/'.$this->SocialLogo;
	else
		$image = ($MyGroup['GroupPic']=='') ? URL.'/img/brandlogoFb.png' : IMGPATH.'/grouppics/medium/'.$groupimg;

	echo '<meta property="og:url" content="'.$url.'" /><meta property="og:type" content="article" />
	<meta property="og:title" content="'.htmlspecialchars_decode(substr($dbtittle,0,70)).'" />
	<meta property="og:site_name" content="Db-csp" />
	<meta property="og:description" content="'.$dbdiscription.'" />
	<meta property="og:image" content="'.$image.'" />';
	echo '<title>'.strip_tags($dbtittle).'</title>';
}
else 
{
	$url = URL;
	$dbdiscription = $this->getSeoConfiguration->SiteDescription;
	$dbtittle = (empty($dbtittle)) ? $this->getSeoConfiguration->SiteTitle : $dbtittle;
	$dbtittle = strip_tags($dbtittle);

	if($this->SocialLogo!='')
		$image = URL.'/img/'.$this->SocialLogo;
	else
		$image = URL.'/img/brandlogoFb.png';

	echo '<meta property="og:url" content="'.$url.'" />
	<meta property="og:type" content="article" />
	<meta property="og:title" content="'.htmlspecialchars_decode(substr($dbtittle,0,70)).'" />
	<meta property="og:site_name" content="db" />
	<meta property="og:description" content="'.$dbdiscription.'" />
	<meta property="og:image" content="'.$image.'" />';
	echo '<title>'.strip_tags($this->getSeoConfiguration->SiteTitle).'</title>';
}




	echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0, user-scalable = no');
	$storage 	= new Zend_Auth_Storage_Session();
	$data = $storage->read();  
    $resultArray = $checkImage->getConfiguration();

    $favIcon = $resultArray['content'];

    $jsonFav = json_decode($favIcon, true);
   
    $favLogo = $jsonFav['FaviconLogo']; //exit;
    
  ?>
<link rel="icon" type="image/png" href="<?php echo URL.'/images/'. $favLogo; ?>">

<!--<link rel="icon" type="image/png" href="<?php echo URL; ?>/img/favicon.png">-->
<script>
var adminURL = '<?php echo adminURL; ?>';
		var stses = '<?php echo $data['showtagmsg'] ?>';
		var controllernamed = '<?php echo $dbeecontrollers; ?>'; 
		var checkRssContent = '<?php echo $this->tsrss; ?>';
		

  </script>

<?php  
	$robottag  = ($this->g_index == '0') ? '<meta name="robots" content="noindex">' : '';
	echo $robottag;
?>


<?php 	

	if(!empty($dbeecontrollers)   && !empty($dbeecontrollersaction))
	{
		if ($_SERVER['SERVER_NAME'] == 'localhost') {
			$baseurl = URL;
		} else  {
			$baseurl = '';
		}
		?>

<?php echo $this->minifyHeadLink()     
		  ->appendStylesheet($baseurl."/flipclock/css/flipclock.css")
		  ->appendStylesheet($baseurl."/css/ddcolortabs.css")
		  ->appendStylesheet($baseurl."/css/tabcontent.css")
		  ->appendStylesheet($baseurl."/css/styles.css")
		  ->appendStylesheet($baseurl."/css/jquery.css")
		  ->appendStylesheet($baseurl."/css/shadowbox.css")
		  ->appendStylesheet($baseurl."/css/tooltip.css")
		  ->appendStylesheet($baseurl."/css1/dropzone.css")
		  ->appendStylesheet($baseurl."/css1/perfect-scrollbar.css")
		  ->appendStylesheet($baseurl."/css1/flick/jquery-ui.min.css")
		  ->appendStylesheet($baseurl."/js1/flexSlider/flexslider.css")
		  ->appendStylesheet($baseurl."/js1/select2/select2.css")
		  ->appendStylesheet($baseurl."/css1/jquery.mentionsInput.css")
		  ->appendStylesheet($baseurl."/css/liteaccordion.css")
		  ->appendStylesheet($baseurl."/css/jquery.autocomplete.css")
		  ->appendStylesheet($baseurl."/js/tagit/jquery.tagit.css")
		  ->appendStylesheet($baseurl."/css/tagit.ui-zendesk.css")
		  ->appendStylesheet($baseurl."/tokeninput/styles/token-input.css")
		  ->appendStylesheet($baseurl."/tokeninput/styles/token-input-facebook.css")		  
		  ->appendStylesheet($baseurl."/css1/dbee.css")
		  ->appendStylesheet($baseurl."/css1/dbchat.css")
		  ->appendStylesheet($baseurl."/css1/dbcrop.css");  ?>

		  <!--[if lt IE 10]>
		<link href="<?php echo URL."/css1/dbee-ie.css";?>?v=<?php echo filemtime('css1/dbee-ie.css');?>" rel="stylesheet" type="text/css" media="all"/>
		<![endif]-->
		<?php if($dbeecontrollers!='findex' && $dbeecontrollers!='index'){?>
			<link href="<?php echo URL."/customcss";?>" rel="stylesheet" type="text/css" media="all"/>
		<?php } if($this->session_data['UserID']!='' && $dbeecontrollers!='findex' && $dbeecontrollers!='index'){?>
				
			<link href="<?php echo URL."/plateformcss";?>" rel="stylesheet" type="text/css" media="all"/>	
		<?php } ?>

 <script src="<?php echo URL."/js1/jquery-2.0.3.min.js"; ?>?v=<?php echo filemtime('js1/jquery-2.0.3.min.js');?>"></script>
<script src="<?php echo URL."/js1/jquery-ui.min.js"; ?>?v=<?php echo filemtime('js1/jquery-ui.min.js');?>"></script>
<script src="<?php echo URL."/js1/jquery.ui.touch-punch.min.js"; ?>?v=<?php echo filemtime('js1/jquery.ui.touch-punch.min.js');?>"></script>
<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jstimezonedetect/1.0.4/jstz.min.js">
</script>
<script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/E-v1.js" async></script>


<script type="text/javascript">
	var tz = jstz.determine(); // Determines the time zone of the browser client
	//console.log(tz);
    var timezone = tz.name(); //'Asia/Kolhata' for Indian Time.
    //alert(timezone);
</script>
<script type="text/javascript">
var userID = '<?php echo $data["UserID"]; ?>';
var TAKEATOUR = '<?php echo $data["takeatour"]; ?>';

		
</script>

 <?php echo $this->minifyHeadScript()
		  ->appendFile($baseurl.'/js/shadowbox/shadowbox.js')	   
		  ->appendFile($baseurl.'/js/browser_check.js')	   
		  ->appendFile($baseurl.'/js/dropdowntabs.js')	   
		  ->appendFile($baseurl.'/js1/flash_detect_min.js')
		  ->appendFile($baseurl.'/js1/select2/select2.min.js')	   
		  ->appendFile($baseurl.'/js1/common.js')
		  ->appendFile($baseurl.'/js1/expert.js')
		  ->appendFile($baseurl.'/js/functions.js')	   
		  ->appendFile($baseurl.'/js1/league.js')	   
		  ->appendFile($baseurl.'/js1/dropzone.min.js')	    
		  ->appendFile($baseurl.'/js1/jquery.nicescroll.min.js')	    
		  ->appendFile($baseurl.'/js1/jquery.timeago.js')	    
		  ->appendFile($baseurl.'/js/html5.js')	    
		  ->appendFile($baseurl.'/js/jsformyhome.js')	    
		  ->appendFile($baseurl.'/js1/jsfornotification.js')	    
		  ->appendFile($baseurl.'/js/dropdowncontent.js')	    
		  ->appendFile($baseurl.'/js1/mainddb.js')	    
		  ->appendFile($baseurl.'/js1/jquery.mousewheel.js')	    
		  ->appendFile($baseurl.'/js1/perfect-scrollbar.js')	    
		  ->appendFile($baseurl.'/js1/jquery-ui-timepicker-addon.js')	    
		  ->appendFile($baseurl.'/flipclock/js/libs/base.js')	    
		  ->appendFile($baseurl.'/flipclock/js/libs/flipclock.js')	    
		  ->appendFile($baseurl.'/flipclock/js/faces/dailycounter.js')	    
		  ->appendFile($baseurl.'/js/strength.js')	    
		  ->appendFile($baseurl.'/js/autocomplete/jquery-migrate-1.0.0.js')	    
		  ->appendFile($baseurl.'/js/autocomplete/jquery.autocomplete.js')	    
		  ->appendFile($baseurl.'/js1/facebook.js')	    
		  ->appendFile($baseurl.'/js1/groupfunctions.js')	    
		  ->appendFile($baseurl.'/js1/profile.js')	    
		  ->appendFile($baseurl.'/js1/social.js')
		  ->appendFile($baseurl.'/js1/jquery.cookie.js')	    
		  ->appendFile($baseurl.'/js1/jquery.elastic.js')     
		  ->appendFile($baseurl.'/tokeninput/src/jquery.tokeninput.js')    
		  ->appendFile($baseurl.'/js/strength.js')
		  ->appendFile($baseurl.'/js1/dbcrop.js')
		  ->appendFile($baseurl.'/js1/dbeelist.js');
   ?>
		

		<script src="<?php echo URL."/js1/jquery.timeTo.min.js"; ?>?v=<?php echo filemtime('js1/jquery.timeTo.min.js');?>"></script>		
		<script src="<?php echo URL."/js1/tag-it.js"; ?>?v=<?php echo filemtime('js1/jquery.timeTo.min.js');?>"></script>		
		<script src="<?php echo URL."/js1/flexSlider/jquery.flexslider-min.js"; ?>?v=<?php echo filemtime('js1/flexSlider/jquery.flexslider-min.js');?>"></script>
		<script src="<?php echo URL."/js1/underscore-min.js"; ?>" type='text/javascript'></script>	
		<script src="<?php echo URL."/js/progressive-image.js"; ?>" type='text/javascript'></script>
		<script>
	    $(function(){
	      $('.progressive-image').progressiveImage(); 
	    });
	    $(window).on('resize', function(){
	      $('.progressive-image').progressiveImage(); 
	    });
	  </script>
		
		<!--it is for web performnace, external url if css and javascript-->
		<?php  $fontFamily =  $this->configuration->fontFamily;
		     if($fontFamily!=''){
		       echo  '<link href="https://fonts.googleapis.com/css?family=Oswald|Lato|Source+Sans+Pro|Montserrat|Raleway|Arimo|Dosis|Hind|Josefin+Sans" media="screen" rel="stylesheet" type="text/css" >';
		      }
		     ?>

		<script charset="ISO-8859-1" src="//fast.wistia.com/assets/external/E-v1.js" async></script>
		<!--it is for web performnace, external url if css and javascript-->
		

		<script type="text/javascript">
		<?php 
			if($dbeecontrollers == 'dashboarduser')
			{	?>

			var ISUSERPROFILE = true;
			 <?php }else{ ?>
				var ISUSERPROFILE = false;
			<?php }
			?>	
		$(document).ready(function(){
			 
			<?php if(isset($_GET['qt'])){ ?>
			socialFeedlayout('my feed','<?php echo (int)$_GET["qt"]; ?>');
			<?php } ?>

			<?php 

			if(isset($data['UserID']) && $dbeecontrollers!='findex') 
			{ 
				$userinfo = $this->msguserhelper($data['UserID']);
				if(($userinfo['usertype']!= 0 && $userinfo['usertype']!= 10 && $userinfo['usertype']!= 100) && $userinfo['Gender']==''){ ?>
					$.showvippopup(<?php echo $data['UserID'];?>,'<?php echo $this->myclientdetails->customDecoding($data['Name']);?>');
				<?php } else { ?>
					TAKEATOUR = parseInt(<?php echo $userinfo["takeatour"]?>);
						setTimeout(function (){
							if(TAKEATOUR!=1) $takeTour();
						},500);
				<?php }
			}?>	

		});

		</script>		
			
		<script language="javascript" type="text/javascript">
			<?php
			if($this->session_data['UserID']!='')
			{
				$uName = ($this->session_data['full_name']!='') ? $this->session_data['full_name'] : $this->session_data['Name']
				?>
						var SESS_USER_NAME 		=  "<?php echo $this->myclientdetails->customDecoding($uName); ?>";
				<?php
			}
			?>		
			var isMobile = navigator.userAgent.match(/(iPad)|(iPhone)|(iPod)|(android)|(webOS)/i);
        	//var userpic				=	"";
        	var PAGE_DBEE_ID		=  "<?php echo $dbdetail_obj['DbeeID'] ?>";
        	var userpic				=	"";
        	var SESS_USER_ID 		=  "<?php echo $this->session_data['UserID']; ?>";        	
        		userpic 			=  "<?php echo $this->session_data['ProfilePic']; ?>";
        	var SERVER_NAME 		= 	"<?php echo $_SERVER['SERVER_NAME'] ?>"
        	var SESS2_USER_ID 		=  "<?php echo adminID; ?>";
        	var clientID 			=  "<?php echo clientID; ?>";
        	var AGCLIENTID 			=  "<?php echo AGCLIENTID; ?>";
			var BASE_URL 			= '<?php echo URL; ?>';
			var IMGPATH 			= '<?php echo IMGPATH; ?>';     
			var PAGE_NUM 			= '<?php echo PAGE_NUM; ?>';  
			var BASE_URL_IMAGES 	= '<?php echo BASE_URL_IMAGES; ?>';  
			var socialActive 		= '<?php echo $this->ShowWarningPopup; ?>'; 
			var Social_Block 		= '<?php echo $this->Social_Block; ?>'; 
			var Socialtype 		    = '<?php echo $this->session_data["Socialtype"]; ?>'; 
			var allSocialstatus 	= '<?php echo $this->socialloginabilitydetail["allSocialstatus"]; ?>'; 
			var getCategoryList 	='';
			var getGroupList 		='';
			var getUserSetList		='';
			var getLeagueList 		='';
			var AttachLink 			='';
			var geteventList        ='';
			var siteHeadTitle       =  '';
			var localTick           = true;
			var mySocialFeedData = {};
			var dbTypeDetails = "<?php echo $dbdetail_obj['Type'] ?>";
			var storeNotifications = false;
			var storeNotificationsmsg = false;
			var profileholderId = '<?php echo $this->userid;?>';
			$(function(){
				if(isMobile!=null){
					$('html').addClass('deviceOn');
				}

				$('.popularTagsListing .hasTagCloud').each(function(index, el) {
	                    $(this).css({
	                        //fontSize: Math.floor((Math.random() * 30) + 10)

	                    })
                     });

				if($('#login').val()!='')
				{
					$.post(
					    BASE_URL+'/myhome/getdefaultlists',{},function(response) {	
						//var response = $.parseJSON(data);
							getCategoryList		=	response.cat;
							getLeagueList		=	response.leage;
							getUserSetList	 	=	response.userset;
							getGrpCatList		=	response.groupcat;
							geteventList		=	response.events;
							getCatSortSearch	=	response.catsearch;
							

							// feeling to left nav category directoly, decrease 1 request to server
							$('#category-options').html(getCatSortSearch);
			                $('#dbfeedfilterbycatWrp').perfectScrollbar({
			                    wheelSpeed: 100
			                });
			                //******
						});
					$.post(
					    BASE_URL+'/myhome/getusrgrouplist',{},function(response) {	
						//var response = $.parseJSON(data);
							getGroupList	=	response.group;
						});
				}
				//leftNavSearchCats(getCatSortSearch);
				//fillcategory();
			});
				
			var adminID = '<?php echo adminID; ?>';
		</script> 

		<script src="<?php echo URL."/js1/jquery.mentionsInput.js"; ?>" type='text/javascript'></script>
		
		<?php if($dbeecontrollers == 'Group' || $dbeecontrollers == 'profile' || $dbeecontrollers == 'Dashboarduser' || $dbeecontrollers == 'dbleagues'){ ?>
		<script src="<?php echo URL;?>/js/liteaccordion/liteaccordion.jquery.js" type='text/javascript'></script>
		<script src="<?php echo URL;?>/js/liteaccordion/jquery.easing.1.3.js" type='text/javascript'></script>
		<?php }
		if($data['UserID']!='') {  ?>
		<script src="<?php echo URL;?>/js1/socket.io.js" type='text/javascript'></script>  
		 <script src="<?php echo URL;?>/js1/app.js" type='text/javascript'></script>  
		 
		 <script src="<?php echo URL."/js1/dbchatlive.js"; ?>" type='text/javascript'></script>
		 <script src="<?php echo URL;?>/js1/dashboard.js" type='text/javascript'></script>
		 <?php //if ($_SERVER['SERVER_NAME'] != 'localhost') { ?>     
		
		 <?php //} ?> 

	      <!-- AUTOCOMPLETE SEARCH -->	 
	      <script language="javascript" type="text/javascript">
	         $(document).ready(function() { 
         	$('[name="searchword"]').autocomplete(BASE_URL+"/myhome/searchmain", {         		
         		matchContains: true,         	
         		minChars: 3,         		
         		selectFirst: false,
         		resultsClass: 'ac_results mainHeaderSearch'

         	});


           //$('.mentionATag').css({"background": "none repeat scroll 0 0 #d7d7d7", "padding": "1px 2px", "color": "#666"});
        
			
         	$('[name="searchword"]').result(function(event, data, formatted) {
				
         		$('[name="searchid"]').val(data[2]);
         	})

           /* $('form#searchform').submit(function(e) { 
              var txtval = $('.searchwordani').val();
              
              if($.trim(txtval) == ''){
              	$dbConfirm({content:'Please type a keyword or user name to search', yes:false});
                return false;
              }
              else
              {
              	 
              }

            });
*/
	
            $('[name="searchword"]').keydown(function(e) {
            	e.stopPropagation();
		        if (e.keyCode == 13) {
		        	 var txtval = $.trim($(this).val());
		        	  if( txtval== ''){
				          	$dbConfirm({content:'Please type a keyword or user name to search', yes:false});
				          	return false;
				           
				          }else{
				          	if (txtval.length < 3) 
				              {
				              	$dbConfirm({content:'Please type at least 3 characters', yes:false});
			                    return false;
				              }
				          }
		        	$('form#searchform').submit();
		        }
		    });
            //var value = $(".trickerContent").text(); // value = 9.61 use $("#text").text() if you are not on select box...
			//value = value.replace("Involve Twitter users", "");
			//$(".trickerContent").text(value);


         });        
         
      </script>
		<?php }
	}

	$showIamLoggedIN =  $_SESSION['User_Session']['loggedIn']; 
	if($showIamLoggedIN==true)
	{
		$_SESSION['User_Session']['loggedIn'] = '';
		?>
		<script type="text/javascript">
			$(document).ready(function() {
				$.usergoesoffline(1) // User comes online
			});  
		</script>	
		<?php
	}
	//echo "<pre>"; print_r($_SESSION);
	//exit;
?>
<input type="hidden" id="ShowRSS" value="<?php echo $this->ShowRSS; ?>">
<input type="hidden" id="allowedPostWithTwitter" value="<?php echo $this->allowedPostWithTwitter; ?>">
<input type="hidden" id="dbeecontrollers" value="<?php echo $dbeecontrollers; ?>">
<input type="hidden" id="dbeecontrollersaction" value="<?php echo $dbeecontrollersaction; ?>">
<input type="hidden" id="addtocontacthidden" value="<?php echo $this->addtocontact; ?>">
<input type="hidden" id="allSocialstatus" value="<?php echo $this->socialloginabilitydetail['allSocialstatus']; ?>">
<input type="hidden" id="Facebookstatus" value="<?php echo $this->socialloginabilitydetail['Facebookstatus']; ?>">
<input type="hidden" id="Twitterstatus" value="<?php echo $this->socialloginabilitydetail['Twitterstatus']; ?>">
<input type="hidden" id="Linkedinstatus" value="<?php echo $this->socialloginabilitydetail['Linkedinstatus']; ?>">
<input type="hidden" id="rssadded" value="" />
<input type="hidden" id="chktagval" value="<?php echo $data['showtagmsg'] ?>" />
<?php 

if($dbeecontrollers != 'index' && $dbeecontrollers != 'error' && $dbeecontrollers != 'findex') // start of checking controllers
{ 
	if($data['UserID']){
	$myhomeObj	=	new Application_Model_Myhome(); 	
	$usersdata 	=	$myclientdetails->getfieldsfromtable(array('Username','Name','ProfilePic','newfeatures','chatstatus','Status'),'tblUsers','UserID',$data['UserID']); 



	if($usersdata[0]['Status']==0 || $usersdata[0]['Status']=='' )
	{ 
		?>
		<script language="javascript" type="text/javascript"> $(document).ready(function(){ gologout(); })  </script>
		<?php
	}

	?>
	<input type="hidden" id="captcha" value="<?php echo trim(md5(time())); ?>"> 
	<script language="javascript" type="text/javascript">
	var ScoreIcon1 = '<?php echo $this->myclientdetails->ShowScoreIcon($this->post_score_setting[1]["ScoreIcon1"], "fa-lg"); ?>';
	var ScoreIcon2 = '<?php echo $this->myclientdetails->ShowScoreIcon($this->post_score_setting[2]["ScoreIcon2"]); ?>';
	var ScoreIcon3 = '<?php echo $this->myclientdetails->ShowScoreIcon($this->post_score_setting[3]["ScoreIcon3"]); ?>';
	var ScoreIcon4 = '<?php echo $this->myclientdetails->ShowScoreIcon($this->post_score_setting[4]["ScoreIcon4"], "fa-lg"); ?>';
	var CHAT_STATUS = "<?php echo $usersdata[0]['chatstatus'];?>";
	$(document).ready(function(){ 
	chkactivitynotification(1);
	});
	var chkactid;
	function startactInt() {
	     //chkactid = setInterval("chkactivitynotification(1)",6000);
	}
	//startactInt();

	function clearactInt() {
	 /*clearInterval(chkactid);
	 chkactid = 0;*/
	}



	</script>
	<input type="hidden" name="login" id="login" value="<?php echo $data['UserID']; ?>">
	<input type="hidden" name="LName" id="LName" value="<?php echo $myclientdetails->customDecoding($data['lname']); ?>">
	<?php }else{  ?>
	<input type="hidden" name="login" id="login" value="">
	<?php } ?>
	<meta name="google-translate-customization" content="2ebbb6097d0e98f0-54f4bf9015c429bd-gc1f356a818db4e17-b" />

	<?php

	if($dbdetail_obj['GroupID']!=0){
		$groupModel = new Application_Model_Groups();
		$Row = $groupModel->selectgroupprivacy($dbdetail_obj['GroupID']);
		if($Row[0]['GroupBgPic']!='')
			$style="background:url('".IMGPATH."/grouppics/medium/".$Row[0]['GroupBgPic']."') 50% 50% no-repeat; background-attachment: fixed; background-size:cover;";
		else
		{ 
		if($this->configuration->backgroundimage!='')
			$style="background:url('".BASE_URL."/img/".$this->configuration->backgroundimage."') 50% 50% no-repeat; background-attachment: fixed; background-size:cover;";
			else
				$styleColor="background-color:".$this->configuration->backgroundColor.";";
		}
	}
	else if($dbeecontrollers == 'group' && $this->grouptypes[0]['GroupBgPic']!=''){
		if($this->grouptypes[0]['GroupBgPic']!='')
			$style="background:url('".IMGPATH."/grouppics/medium/".$this->grouptypes[0]['GroupBgPic']."') 50% 50% no-repeat; background-attachment: fixed; background-size:cover;";
		else
			$styleColor="background-color:".$this->eventResult[0]['bgcolor'].";";
	}
	else if($dbdetail_obj['events']!=0)
	{
		$event = new Application_Model_Event();
		$Row = $event->getEvent($dbdetail_obj['events']);
		if($Row[0]['bgimage']!='')
			$style="background:url('".BASE_URL."/event/".$Row[0]['bgimage']."') 50% 50% no-repeat; background-attachment: fixed; background-size:cover;";
		else if($Row[0]['bgcolor']!='')
			$styleColor="background-color:".$Row[0]['bgcolor'].";";
		else
		{ 
			if($this->configuration->backgroundimage!='')
				$style="background:url('".BASE_URL."/img/".$this->configuration->backgroundimage."') 50% 50% no-repeat; background-attachment: fixed; background-size:cover;";
			else
				$styleColor="background-color:".$this->configuration->backgroundColor.";";
		}
	}
	else if($dbeecontrollers == 'event'){
		if($this->eventResult[0]['bgimage']!='')
			$style="background:url('".BASE_URL."/event/".$this->eventResult[0]['bgimage']."') 50% 50% no-repeat; background-attachment: fixed; background-size:cover;";
		else
			$styleColor="background-color:".$this->eventResult[0]['bgcolor'].";";
	}else{ 
		if($this->configuration->backgroundimage!='')
			$style="background:url('".BASE_URL."/img/".$this->configuration->backgroundimage."') 50% 50% no-repeat; background-attachment: fixed; background-size:cover;";
		else
			$styleColor="background-color:".$this->configuration->backgroundColor.";";
	}

	if($dbeecontrollers == 'message'){?>
	<script src="<?php echo URL."/js1/msgsearch.js"; ?>?v=<?php echo filemtime('js1/msgsearch.js');?>"></script>
	<?php }

}// End of checking controllers
		
  ?>

</head>