<?php 
if(clientID==19) include "agheader.phtml";
else include "header.phtml";

include "content.phtml";

include "footer.phtml";
	/* echo $this->render('header.phtml') ;
	echo $this->layout()->content; 
	echo '</div></div></div>';
	echo $this->render('footer.phtml') ;
	echo'</body></html>';  */
//end of this <div id="pageContent" page-type="homepage"> stated on header.phtml
	//echo $this->render('footer.phtml') ;
	

?>

