<input type="hidden" id="curr-notification-count">

<input type="hidden" id="notifications-top-hidden" value="<?=($_COOKIE['newdbcount-ghst']=='') ? '0' : $_COOKIE['newdbcount-ghst'];?>">

<input type="hidden" id="notifications-top-score-hidden" value="<?=($_COOKIE['newdbcountscore-ghst']=='') ? '0' : $_COOKIE['newdbcountscore-ghst'];?>">

<input type="hidden" id="notifications-top-comment-hidden" value="<?=($_COOKIE['newcommentcount-ghst']=='') ? '0' : $_COOKIE['newcommentcount-ghst'];?>">

<input type="hidden" id="notifications-top-msg-hidden" value="<?=($_COOKIE['newmsgcount-ghst']=='') ? '0' : $_COOKIE['newmsgcount-ghst'];?>">

<input type="hidden" id="notifications-top-grpinvite-hidden" value="<?=($_COOKIE['newgrpinvitecount-ghst']=='') ? '0' : $_COOKIE['newgrpinvitecount-ghst'];?>">

<input type="hidden" id="notifications-top-grpreq-hidden" value="<?=($_COOKIE['newgrpreqcount-ghst']=='') ? '0' : $_COOKIE['newgrpreqcount-ghst'];?>">

