<?php 
	$commonmodel_obj      = new Application_Model_Commonfunctionality();
?>
<script>
$(function() {
	fetchadvert();
	$('.leaguesPostScores a[datatype="love"]').trigger('click');

		
		$('body').on('click','#mainActDect',function(event) {
			accountSetttingPopup('scoring');
		});

		//dashboardprofile('<?php echo $this->user;?>',1);
	scoreProfile('<?php echo $this->user;?>','#dashboarduserDetails');
		//fillcategory();
	//seeuserscoreposition('love',<?php echo $this->user ?>,'lovelikepostion');
	/*seeuserscoreposition('philosopher',<?php echo $this->user ?>,'fotpostion');
	seeuserscoreposition('rogue',<?php echo $this->user ?>,'hatepostion');*/
});
</script>
<input type="hidden" id="noti-type" value="1">
<input type="hidden" id="dbeeuser" value="<?php echo $this->user ?>">

<input type="hidden" id="dbeepopchk" value="1">
<input type="hidden" id="frompop" value="0">



		


	<div id="leftListing">
		<div id="dbee-feeds">
			<div class="dashboarprofleWrp" style="height:auto">
			<div class="middleDescriptionBox">
				<h2>Hi <?php echo $this->myclientdetails->customDecoding($this->session_data['Name']).' '.$this->myclientdetails->customDecoding($this->session_data['lname']); ?>, welcome to your leagues :-)</h2>
				<p>All users posts and comments can be scored from 5 options...</p>
				<div class="scrptnRow">
					<div>Score option</div>
					<div>League</div>
				</div>
				<div class="scrptnRow" style="background:#f8b53a;">
					<div>
						<span><i>Love</i> - carries 5 points</span><br>
						<span><i>Like</i> - carries 1 point</span>
					</div>
					<div class="lg">Loved</div>
				</div>
				<div class="scrptnRow" style="background:#9d9d9c;">
					<div>
						<span><i>Food for thought</i> - carries 1 point</span>
					</div>
					<div class="lg">Philosophers</div>
				</div>
				<div class="scrptnRow" style="background:#bdbdbd;">
					<div>
						<span><i>Dislike</i> - carries 1 point</span><br>
						<span><i>Hate</i> - carries 1 point</span>
					</div>
					<div class="lg">Rogues</div>
				</div>
				<p>But i dont want to be scored! <br>
No problem, you can turn off the ability to be scored and placed into the leagues <a href="#" class="underline" id="mainActDect">here</a></p>

			</div>
			<div class="pstBriefFt"><a href="javascript:void(0);" class="dontShowMeAgain" data-close="How do the leagues work?">OK, got it :-)</a></div>
			</div>
			<div id="dashboarduserDetails" class="dashboarprofleWrp"> </div>
			<div id="leaguesTypes">
			<div class="leaguesPostScores">
				
				<ul class="tabLinks">
					<li><a href="javascript:void(0)" dataType="love"><i class="fa fa-smile-o fa-lg"></i> <?php echo $this->score->score1; ?></a></li>
					<li><a href="javascript:void(0)" dataType="rogue"><i id="hate-dbee" class="fa fa-frown-o fa-lg"></i>  <?php echo $this->score->score2; ?></a></li>
					<li><a href="javascript:void(0)" dataType="philosopher"><i class="fa fa-lightbulb-o fa-lg"></i> <?php echo $this->score->score3; ?></a></li>					
					<?php  if($this->plateform_scoring==0){?>
					<li class="pull-right"><a href="javascript:void(0);" id="myPlatformPositions" secure_uid="<?php echo $this->user ?>" class="btn btn-yellow" >my platform positions</a></li>

					<?php } ?>
				</ul>
			</div>

			<div class="pull-right leaguesPostSortTime">
				<a href="#" class="leaguesPstSorting"><i class="sprite menuIcon"></i> post Sorting</a>
			</div>
		</div>
   
	<div id="leaguesListsContainer">
		<div id="topthree-leagues"> <ul class="leaguesLists"> </ul></div>
		<div id="leagues-feed"> </div>
	</div>
	
		</div>


	</div>	
	

<div id="rightListing">
	<?php echo $commonmodel_obj->displaybroadcastdbs(); ?>
</div>
<div class="clearfix"> </div>