<link rel="stylesheet" href="../../adminraw/css/widgets-style.css">

<h1 class="pageTitle ">Embed feeds</h1>
<div class="jointElement" style="margin:0 0 10px 0;">
    <ul>
      <li class="active" ><a href="javascript:void(0)" data-type="group">Group</a></li>
      <li><a href="javascript:void(0)" data-type="post">Post</a></li>
    </ul>
 </div>

<div class="clearfix"></div>

<!-- <label class="label">Select option: </label>
<select name="widgetoption" id="widgetoption">
    <option value="group">Group</option>
    <option value="post">Post</option>
</select>
 -->
<div class="widgetsWraper">
    <div id="pageContainergroup" class="kcSidebar widgetsDataWrp active">
        <div class="kcSidebarHeader">
            <h2>
                <i class="fa fa-users fa-lg grpIconLarge"></i> 
                <div class="inputSrc"><input type="text"  placeholder="Search" class="groupsearch" id="Widgetgroupsearch"></div>
                <a href="javascript:void(0)" class="fa fa-refresh restAllBox" aria-hidden="true"></a>
            </h2>
        </div>
        <div class="ksfolderlist">
            <ul class="groupbox">
            <?php 
                if(count($this->grouplist) >0 )
                {
                    foreach ($this->grouplist as $key => $value) {
                       
                       echo '<li data-id="'.$value['ID'].'">
                           <input id="grp_'.$value['ID'].'"  type="checkbox" value="'.$value['ID'].'" >
                           <label for="grp_'.$value['ID'].'">' .$value['GroupName'].'</label>
                       </li>';      
                    }
                    if($this->totalgrp > count($this->grouplist)){ ?>
                    <div class="show_more_main" id="show_more_main<?php echo $value['ID']; ?>" style="cursor:pointer;">
                        <span id="<?php echo $value['ID']; ?>" data-type="group" class="show_more" title="Load more groups">Show more</span>
                        <span class="loding" style="display: none;"><span class="loding_txt">Loading….</span></span>
                    </div>
                <?php }  

                }else
                {
                echo"<li>no result found!</li>";
                }
            ?>
            </ul>
        </div>
    </div>

    <div id="pageContainerpost" class="kcSidebar widgetsDataWrp">
        <div class="kcSidebarHeader">
            <h2>
                <i class="fa fa-list fa-lg grpIconLarge"></i> 
                <div class="inputSrc"><input type="text"  placeholder="Search" class="postsearch" id="postsearch"></div>
                <a href="javascript:void(0)" class="fa fa-refresh restAllBox" aria-hidden="true"></a>
            </h2>
           
        </div>
        <div class="ksfolderlist">
            <ul class="groupbox">
            <?php 
                if(count($this->postlist) >0 )
                {
                    foreach ($this->postlist as $key => $value) {

                        if($value['type']==5)
                        {
                            $text=$value['PollText'];
                        }
                        elseif ($value['type']==7) {

                           $text=$value['surveyTitle'];
                        }else
                        {
                            $text=$value['Text'];
                        }
                       
                       echo '<li data-id="'.$value['DbeeID'].'">
                               <input id="pst_'.$value['DbeeID'].'"  type="checkbox" value="'.$value['DbeeID'].'" >
                               <label for="pst_'.$value['DbeeID'].'">' .$text.'</label>
                           </li>';      
                    }

                if($this->totalpost > count($this->postlist)){ ?>
                    <div class="show_more_main" id="show_more_main<?php echo $value['DbeeID']; ?>" style="cursor:pointer;">
                        <span id="<?php echo $value['DbeeID']; ?>" data-type="post" class="show_more" title="Load more groups">Show more</span>
                        <span class="loding" style="display: none;"><span class="loding_txt">Loading….</span></span>
                    </div>
                <?php }  
                }else{
                    echo"<li>no result found!</li>";
                }
            ?>
            </ul>
        </div>
    </div>
    
 <div class="widgetsPreviewWrp">
    <div class="widgetToolWrp">
        <ul>
            <li class="customiseWidgets" style="display:none;"><a href="javascript:void(0)" data-action="theme"><i class="fa fa-paint-brush " aria-hidden="true"></i> <span>Customise</span></a></li>
            <li class="selectWidgetFromOption">
                <select id="selectWidgetFromOption" style="width:150px;" actions="<a href='javascript:void(0)' class='closeBtn'></a>"></select>
                <a href="javascript:void(0)" class="btn btn-yellow" data-action="reset" style="display:none">Reset</a>
            </li>
            <li class="saveWidgets" style="display:none;"><a href="javascript:void(0)" data-action="save"><i class="fa fa-save" aria-hidden="true"></i> <span>Save</span></a></li>
            <li class="getEmbedCode"><a href="javascript:void(0)" data-action="embed"><i class="fa fa-code-fork" aria-hidden="true"></i> <span>Embed</span></a></li>

        </ul>
        <div class="wdSaveWrpInt">
            <div class="svInt"><input type="text" placeholder="Enter feed name"></div>
            <a href="javascript:void(0);" data-action="close"><i class="fa fa-times" aria-hidden="true"></i></a>
            <a href="javascript:void(0);" id="savefeed" data-action="save">save</a>
        </div>
    </div>
    <div class="themeWidgetsWrp">
         <h3>Container <i class="fa fa-chevron-down"></i></h3>
        <ul data-type="widgetBox">
            <li>
                <h4>
                    <span>Border radius <i class="bx bx-yellow">5px</i></span>
                    <input type="range" min="0" max="20" value="5" name="boxBorderRadius" />
                </h4>
            </li>
            <li>
                <h4>
                    <span>Border width <i class="bx bx-yellow">1px</i></span>
                    <input type="range" min="0" max="20" name="boxBorderWidth" value="1" />
                </h4>
            </li>
             <li data-type="borderColor">
                <h4>
                    <span>Border color </span>
                    <a href="javascript:void(0);" class="colorFill"></a>
                    <input type="hidden" name="fntColor">
                </h4>
            </li>
             
        </ul>
          <h3>Title feed <i class="fa fa-chevron-down"></i></h3>
        <ul data-type="title">
            
            <li>
                <input type="text" placeholder="insert widget title" max="50" name="titleWidgets">
            </li>
            <li data-type="backgroundColor">
                <h4>
                    <span>Background color </span>
                    <a href="javascript:void(0);" class="colorFill"></a>
                    <input type="hidden" name="bgColor">
                </h4>
                
            </li>
             <li data-type="color">
                <h4>
                    <span>Font color </span>
                    <a href="javascript:void(0);" class="colorFill"></a>
                    <input type="hidden" name="fntColor">
                </h4>
            </li>
             
        </ul>
         <h3>List style <i class="fa fa-chevron-down"></i></h3>
        <ul data-type="list">
           
            <li data-type="backgroundColor">
                <h4>
                    <span>Background color </span>
                    <a href="javascript:void(0);" class="colorFill"></a>
                    <input type="hidden" name="bgColor">
                </h4>
                
            </li>
             <li data-type="color">
                <h4>
                    <span>Font color </span>
                    <a href="javascript:void(0);" class="colorFill"></a>
                    <input type="hidden" name="fntColor">
                </h4>
            </li>
              <li data-type="borderColor">
                <h4>
                    <span>Border color </span>
                    <a href="javascript:void(0);" class="colorFill"></a>
                    <input type="hidden" name="fntColor">
                </h4>
            </li>
        </ul>
    </div>
    <iframe id="widgetsPreview" src="<?=BASE_URL?>/widgets/feed/index" ></iframe>
 </div>

 </div>



<script type="text/javascript">
var saveMyListDefault = {widgetId:'', name:'',title:'', id:[], randomCode:'', theme:{backgroundColor:'#fff', color:'#333', borderColor:'', titlebackgroundColor:'#fff', titlecolor:'#333', boxBorderWidth:1, boxborderColor:'#ccc', boxBorderRadius:5}};
var saveMyList = {widgetId:'', name:'',title:'', id:[], randomCode:'', theme:{backgroundColor:'#fff', color:'#333', borderColor:'', titlebackgroundColor:'#fff', titlecolor:'#333', boxBorderWidth:1, boxborderColor:'#ccc', boxBorderRadius:5}};

var notFoundTemplate = '';
function stylesheet (saveMyList){

     var iframe = $('#widgetsPreview').contents();
    var styleAppend = 'h1{background:'+saveMyList['theme']['titlebackgroundColor']+'; color:'+saveMyList['theme']['titlecolor']+'; border-radius:'+saveMyList['theme']['boxBorderRadius']+'px '+saveMyList['theme']['boxBorderRadius']+'px 0px 0px;}\
                          .mainCnt{background:'+saveMyList['theme']['backgroundColor']+'; border-color:'+saveMyList['theme']['boxborderColor']+';  border-width:'+saveMyList['theme']['boxBorderWidth']+'px; border-radius:'+saveMyList['theme']['boxBorderRadius']+'px}\
                          .noListInWidget{color:'+saveMyList['theme']['color']+'}\
                        li{\
                            color:'+saveMyList['theme']['color']+';\
                            border-color:'+saveMyList['theme']['borderColor']+'\
                        }';
         $('#stylesheet',iframe).html(styleAppend);

}


 function checkSaveTemlate (){  
  if(saveMyList['randomCode']!=''){
    $('.widgetsWraper').addClass('saveTemplateStatus');
  }else{
    $('.widgetsWraper').removeClass('saveTemplateStatus');
  }
}

function loadJosn(jsonObj){
    saveMyList['randomCode'] = '';
    saveMyList['widgetId'] = '';
    $('input[name="titleWidgets"]').val(jsonObj['title']).keyup();
}
function getListId (removeDataId){
      $('.saveWidgets, .customiseWidgets').show();
      var iframe = $('#widgetsPreview').contents();
         var dataIDIframe = [];
     $('.widgetsDataWrp.active li[data-id="'+removeDataId+'"] input').prop('checked' , false);
     $('.widgetsDataWrp.active li input').prop('checked' , false);
     $('body ul li[data-id]',iframe).each(function (){
        var dataId = $(this).attr('data-id');
            dataIDIframe.push(dataId);
         $('.widgetsDataWrp.active li[data-id="'+dataId+'"] input').prop('checked' , true);
    });

    

    
      saveMyList['id']=dataIDIframe;
     /*$.each( saveMyList['id'], function (i, va){
        $('input', '.widgetsDataWrp.active li[data-id="'+va+'"]').prop('checked' , true);
     });*/
      
      var countList = saveMyList['id'].length;
      if(countList>0){
            $('li.noListInWidget', iframe).remove();
      }else{
        if(saveMyList.widgetId==''){
            $('.saveWidgets, .customiseWidgets').hide();
        }
        $('ul', iframe).html(notFoundTemplate);
        $('.widgetsPreviewWrp').removeClass('activeToolBar');
        
      }
     // console.log(saveMyList['id'].length)
    //console.log(JSON.stringify(saveMyList));
}
$(document).ready(function (){
    $('.themeWidgetsWrp input[type="range"]').change(function(){
        var thisVal = $(this).val();
        var nameInput = $(this).attr('name');
        $(this).closest('h4').find('.bx').text(thisVal+'px');
        saveMyList['theme'][nameInput]= thisVal;
        stylesheet(saveMyList);
    });


    $('.themeWidgetsWrp h3').click(function(){
        $('.themeWidgetsWrp h3').removeClass('active');
        $(this).toggleClass('active');
    });
$('.themeWidgetsWrp h3:first').trigger('click');

   $('.jointElement li a').click(function (){
        var dataType = $(this).attr('data-type');
        $(this).closest('ul').find('.active').removeClass('active');
        var titleOfwidgets = '';
         widgetType = 'group';
        var  widgetTypeID = 0;
                        saveMyList =  JSON.parse(JSON.stringify(saveMyListDefault));

        var iframeurl = $('#widgetsPreview').attr('src');
        $('#widgetsPreview').attr('src', iframeurl);
        $('.widgetsDataWrp input[type="text"], .widgetsPreviewWrp input[type="text"]').val('');
        $('.widgetsDataWrp input[type="checkbox"]').attr('checked', false);
        $('.selectWidgetFromOption .btn[data-action="reset"], .saveWidgets, .customiseWidgets').hide();
          $(this).closest('li').addClass('active');
        $('.widgetsDataWrp').removeClass('active');
            if(dataType=='post'){
                $('#pageContainerpost').addClass('active');
               titleOfwidgets = 'Post feed';
               widgetType = 'post';
               widgetTypeID = 1;
            }else{
                 $('#pageContainergroup').addClass('active');
                  titleOfwidgets = 'Group feed';
            }
             saveMyList['title'] = titleOfwidgets;
             saveMyList['widgetId'] = '';

            $.ajax({
                type:'POST',
                url:BASE_URL + '/admin/widgets/savelist',
                data: {type: widgetTypeID},
                success:function(response){

                    $('#selectWidgetFromOption').html('<option value="0">Load saved feed</option>'+response.content);
                     $select('#selectWidgetFromOption');
                } 
            }); 

          $('#widgetsPreview').load(function (){
                loadJosn(saveMyList);
                var iframe = $(this).contents();
                $('ul .noListInWidget', iframe).remove();
                notFoundTemplate = '<li class="noListInWidget">no '+widgetType+' found </li>';
                $('ul', iframe).html(notFoundTemplate);
                checkSaveTemlate();
                
          });

   });


    $('.colorFill').colpick({
            layout:'hex',
              submit:0,
              colorScheme:'dark',
             onChange:function(hsb,hex,rgb,el,bySetColor) {
               
                $(el).css('backgroundColor', '#' + hex);
                $(el).siblings('input').val('#'+hex);
                var thisType  = $(el).closest('li').attr('data-type');
                var thisTypeCat  = $(el).closest('ul').attr('data-type');
                //$('li',iframe).css(thisType, '#'+hex);
                if(thisTypeCat=='title'){
                    saveMyList['theme']['title'+thisType] = '#'+hex;
                }else if(thisTypeCat=='widgetBox'){
                    //console.log(thisType);
                    saveMyList['theme']['box'+thisType] = '#'+hex;
                }
                else{
                    saveMyList['theme'][thisType] = '#'+hex;
                }
                stylesheet(saveMyList);
            }
        });

    $('input[name="titleWidgets"]').keyup(function(){
        var iframe = $('#widgetsPreview').contents();
        var thisElVal = $(this).val();
        $('h1' ,iframe).text(thisElVal);
    });

    $('.widgetToolWrp li a').click(function (e){
        e.preventDefault();
        var thisEl = $(this);
        var dataA = thisEl.attr('data-action');
        
        if(dataA=='save'){
            $('.wdSaveWrpInt').addClass('active');
            var selectListObj = $('.selectWidgetFromOption select');
            var selectListObjVal = selectListObj.val();
            if(selectListObjVal==0){
                myWidgetsName = '';
            }else{
               myWidgetsName =  $('option[value="'+selectListObjVal+'"]',selectListObj).text();
            }
            $('.wdSaveWrpInt input').val(myWidgetsName);
            
        }else if(dataA=='embed'){
            $('.wdSaveWrpInt').addClass('active');
            var myEmbedCode = '<iframe src="'+BASE_URL+'/widgets/feed/index/code/'+saveMyList['randomCode']+'" width="100%" height="200"></iframe>';
            $('.wdSaveWrpInt').addClass('activeEmbed');
            $('.wdSaveWrpInt input').val(myEmbedCode);
        }
        else if(dataA=='theme'){
            $('.widgetsPreviewWrp').toggleClass('activeToolBar');
        }
        else if(dataA=='reset'){
          $('.jointElement li.active a').trigger('click');           
        }
    });
     $('.wdSaveWrpInt a').click(function (e){
        e.preventDefault();
        var thisEl = $(this);
        var dataA = thisEl.attr('data-action');
        var pr = thisEl.closest('.wdSaveWrpInt');
        if(dataA=='save'){
              var dataType = $('.jointElement .active').text();
              var dataId = thisEl.closest('li').attr('data-id');
              var selectListObj = $('.selectWidgetFromOption select');
              var selectListObjVal = selectListObj.val();
              var name = $.trim($('input',pr).val());
              if(name==''){
                 $messageError('sorry! widget Name is blank');
                return false;
              }
              saveMyList['name'] = name;
              saveMyList['type'] = dataType;
              saveMyList['title'] = $('input[name="titleWidgets"]').val();
              //saveMyList['id'] = [];
            /*  $('.widgetsDataWrp.active .ksfolderlist li input:checked').each(function (i, v){
                 saveMyList['id'].push($(this).val());
              });*/
             getListId();
            //console.log( JSON.stringify(saveMyList));
               $.ajax({
                type:'POST',
                url:BASE_URL + '/admin/widgets/insertcode',
                data: {widgetjson: JSON.stringify(saveMyList)},
                success:function(response){

                 //   console.log()
                 $('.wdSaveWrpInt a[data-action="close"]').trigger('click'); 
                 //console.log(saveMyList['widgetId']);
                  if(saveMyList['widgetId']==''){
                    $('.selectWidgetFromOption select').append('<option value="'+response.widgetID+'" selected>'+name+'</option');
                    $select('.selectWidgetFromOption select');
                    saveMyList['widgetId'] = response.widgetID;
                    saveMyList['randomCode'] =response.rand_code;
                    //console.log(JSON.stringify(saveMyList));
                    checkSaveTemlate();
                      $messageSuccess('Save successfully');

                  }
                }
            }); 
               
        }else{
            $('.wdSaveWrpInt').addClass('removeActive').removeClass('active');
            setTimeout(function (){
                 $('.wdSaveWrpInt').removeClass('activeEmbed removeActive');
            },1000);
        }
    });

   /* $('#widgetsPreview').load(function (){
        $(this).css({height:$('.widgetsDataWrp').height()});
    });*/
        

    $('body').on('click', '.widgetsDataWrp .ksfolderlist li label', function (e){
      e.preventDefault();
        var iframe = $('#widgetsPreview').contents();
        var thisEl = $(this);
        var thisElVal = thisEl.text();
        var intpBox =  thisEl.prev('input');
        var dataId = thisEl.closest('li').attr('data-id');
        if(intpBox.is(':checked')==true){
            $('body ul li[data-id="'+dataId+'"]', iframe).removeClass('activeList').remove();
        }else{
            $('body ul', iframe).prepend('<li data-id="'+dataId+'" class="activeList"><a href="javascript:void(0)" class="closeBtn">&#10006;</a><span>'+thisElVal+'</span></li>');
        }
       
        getListId();

       // iframeH = $('html',iframe).height();
       //$('#widgetsPreview').css({height:iframeH});


    });


    $('body').on('click','.show_more_main',function(){
        
        var thisEl  = $(this);
        var pr  = thisEl.closest( ".widgetsDataWrp");
        var moreEl = $('.show_more', thisEl);
        var ID = moreEl.attr('id');
        var type = moreEl.attr('data-type');
        moreEl.hide();
        $('.loding', thisEl).show();
        var URL = BASE_URL + '/admin/widgets/feedmore';
        $.ajax({
            type:'POST',
            url:URL,
            data: {'lastId': ID,'optiontype':type},
            success:function(response){
                if(type=='group'){
                    $('.ksfolderlist ul', pr).append(response.content);
                     thisEl.remove();
                }
                if(type=='post'){
                 $('.ksfolderlist ul', pr).append(response.content);   
                 thisEl.remove();
                }
                getListId();
                 
            }
        }); 
    });
    $('.jointElement li:first a').trigger('click');


    $('.widgetsDataWrp .inputSrc input').keypress(function(e){
      var keycode = (e.keyCode ? e.keyCode : e.which);
        if(keycode==13){
            var thisEl  = $(this);
            var pr  = thisEl.closest( ".widgetsDataWrp");
            var searchKeyWord = thisEl.val(); 

            var URL = BASE_URL + '/admin/widgets/groupsearch';
            var dataParam = {groupsearchvalue: searchKeyWord};
            if(widgetType=='post'){
                URL = BASE_URL + '/admin/widgets/postsearch';
                dataParam = {'postsearchvalue': searchKeyWord};
            }
            $.ajax({
                type:'POST',
                url:URL,
                data:dataParam,
                success:function(response){ 
                  if(searchKeyWord!=''){
                      pr.addClass('activeSearchW');
                    }else{
                       pr.removeClass('activeSearchW');
                    }
                    $('.ksfolderlist ul', pr).html(response.content); 
                    getListId();
                    
                                  

                }
            }); 
       }
    });

    $('.restAllBox').click(function (){
       var e = $.Event( "keypress", { which: 13 } );
        $(this).closest('h2').find('input').val('').trigger(e);


    });

    $('#selectWidgetFromOption').on('change', function() {
     
      var widgetID = this.value;
            var URL = BASE_URL + '/admin/widgets/widgetdetail';
            var dataParam = {widgetID: widgetID};
            var iframe = $('#widgetsPreview').contents();
           if(widgetID!=0){

                $.ajax({
                    type:'POST',
                    url:URL,
                    data:dataParam,
                    success:function(response){ 
                     var jsonData =  JSON.parse(response.jsonData);
                     // var jsonData  = JSON.E
                      saveMyList = jsonData;
                      saveMyList['randomCode'] = response.code;
                      saveMyList['widgetId'] = response.widgetID;
                      stylesheet(jsonData);
                      $('body h1' , iframe).html(saveMyList['title']);
                      $('body ul' , iframe).html(response.content);
                       $('.selectWidgetFromOption .btn[data-action="reset"]').show();
                       $('.widgetsDataWrp.active li input').prop('checked' , false);
                      getListId();
                       //console.log(JSON.stringify(saveMyList));     
                       checkSaveTemlate();              

                    }
                }); 
            }else{
                $('.saveTemplateStatus').removeClass('saveTemplateStatus');
                $('.jointElement li.active a').trigger('click');  
            }
    });

    $('body').on('click', '.selectWidgetFromOption .closeBtn', function(event) {
        event.preventDefault();
        event.stopPropagation();
        var thisEl = $(this);
        var widgetID = thisEl.closest('li').attr('rel'); 

        var msg = 'Are you sure you want to delete this feed?';        

        $('#dialogConfirmSetting').remove();
        $('body').append('<div id="dialogConfirmSetting">' + msg + '</div>');

        $("#dialogConfirmSetting").dialog({
            resizable: false,
            title: 'Please confirm',
            width: 400,
            modal: true,
            buttons: {
                "Yes": function() {
                    $(this).dialog("close");
                    $.ajax({
                        url: BASE_URL + "/admin/widgets/deletewidget",
                        data: {'widgetID':widgetID},
                        type: "POST",
                        success: function(data) {
                            thisEl.closest('.select').find('option[value="'+widgetID+'"]').remove();
                            $select('#selectWidgetFromOption');
                            $messageSuccess('Feed deleted successfully');                           
                          

                        }
                    });
                }
            }
        });

    });

});
</script>