<?php echo $this->doctype() ?>

<html xmlns="http://www.w3.org/1999/xhtml">

<head>

<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />

<title>dbee.me | the debate n rate social network</title>

<meta name="description" content="dbee is a real time 'debate and rate' social network enabling you to share views on any subject, in open community or private groups. Create debate by posting opinions, photos, videos and links, score and be scored on posts, and rise or fall in dbee leagues.">

<meta property="og:url" content="http://www.dbee.me.com" /> 

<meta property="og:type" content="article" /> 

<meta property="og:title" content="dbee.me | the debate n rate social network" /> 

<meta property="og:site_name" content="dbee" /> 

<meta property="og:description" content="dbee is a real time 'debate and rate' social network enabling you to share views on any subject, in open community or private groups. Create debate by posting opinions, photos, videos and links, score and be scored on posts, and rise or fall in dbee leagues." /> 

<meta property="og:image" content="http://www.dbee.me/images/landing-logo.png" />

<link rel="icon" type="image/png" href="http://dbee.me/images/favicon.png">



<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => 'http://dbee.me/images/favicon.png'))

                       // ->prependStylesheet(BASE_URL . '/css/bootstrap-responsive.min.css')

                        ->prependStylesheet(BASE_URL . '/css/style.css')

                        ->prependStylesheet(BASE_URL . '/css/global.css')

                       // ->prependStylesheet(BASE_URL . '/css/bootstrap.min.css')

						->prependStylesheet(BASE_URL . '/css/speechbubbles.css')					

						->prependStylesheet(BASE_URL . '/css/ddcolortabs.css')					

						->prependStylesheet(BASE_URL . '/css/tabcontent.css')

						->prependStylesheet(BASE_URL . '/css/styles.css')

						->prependStylesheet(BASE_URL . '/css/dbee.css')						

						->prependStylesheet(BASE_URL . '/css/jquery.css')

						->prependStylesheet(BASE_URL . '/css/jquery.blockUI.css')

						->prependStylesheet(BASE_URL . '/css/shadowbox.css')

						->prependStylesheet(BASE_URL . '/css/dbee.css')						

						?>

<!-- Scripts -->

<?php echo $this->headScript()->prependFile(BASE_URL . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))

                     // ->prependFile(BASE_URL . '/js/bootstrap.min.js')

					  ->prependFile(BASE_URL . '/js/smooth.pack.js')

                      ->prependFile(BASE_URL . '/js/jquery.min.js')

				      ->prependFile(BASE_URL . '/js/functions.js')

				      ->prependFile(BASE_URL . '/js/browser_check.js')

				      ->prependFile(BASE_URL . '/js/ajaxupload.js')

				      ->prependFile(BASE_URL . '/js/jquery-latest.js')

				      ->prependFile(BASE_URL . '/js/jquery.min_1.4.4.js')

				      ->prependFile(BASE_URL . '/js/jquery.min_1.4.js')

				      ->prependFile(BASE_URL . '/js/jquery.slideto.v1.1.js')	

				      //->prependFile(BASE_URL . '/js/shadowbox/show_shadowbox.js')

				      //->prependFile(BASE_URL . '/js/shadowbox/shadowbox.js')				      

				      ->prependFile(BASE_URL . '/js/all.js')				

				      ->prependFile(BASE_URL . '/js/ddaccordion.js')

				      ->prependFile(BASE_URL . '/js/dropdowncontent.js')

				      ->prependFile(BASE_URL . '/js/dropdowntabs.js')	

				      ->prependFile(BASE_URL . '/js/html5.js')

				      ->prependFile(BASE_URL . '/js/javascript.js')

				      ->prependFile(BASE_URL . '/js/jquery.blockUI.js')

				      ->prependFile(BASE_URL . '/js/tabcontent.js')

				      ->prependFile(BASE_URL . '/js/speechbubbles.js')

				      ->prependFile(BASE_URL . '/js/jquery.js')

				    				   

				      ?>







<script language="javascript" type="text/javascript">

var screenwidth = screen.width;

if (screenwidth == 1024) {

	document.write('<link rel="stylesheet" href="<?php echo BASE_URL.'css/1024.css'?>" type="text/css" media="all" />');

}

</script>





<script language="javascript" type="text/javascript" src="<?php echo BASE_URL.'js/functions.js?1379088342'?>"></script>

<script type="text/javascript" src="<?php echo BASE_URL.'js/browser_check.js'?>"></script>

<script type="text/javascript" src="<?php echo BASE_URL.'js/smooth.pack.js'?>"></script>



<!-- BEGIN INCLUDE SCRIPTS TO CALL SHADOWBOX -->



<script type="text/javascript" src="<?php echo BASE_URL.'js/shadowbox/shadowbox.js'?>"></script>

<script type="text/javascript" src="<?php echo BASE_URL.'js/shadowbox/show_shadowbox.js'?>"></script>

<!-- END INCLUDE SCRIPTS TO CALL SHADOWBOX -->



<!-- DROPDOWN CONTENT FOR MY GROUP OPTIONS -->

<script type="text/javascript" src="<?php echo BASE_URL.'js/dropdowncontent/dropdowncontent.js'?>"></script>

<!-- DROPDOWN CONTENT FOR MY GROUP OPTIONS -->



<!-- DROPDOWN TOP MENU -->

<script type="text/javascript" src="<?php echo BASE_URL.'js/dropdowntab/dropdowntabs.js'?>"></script>

<!-- DROPDOWN TOP MENU -->



<!-- BEGIN INCLUDE SCRIPTS TO CALL DHTML TOOLTIP -->

<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.'css/speechbubbles.css'?>" />

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js"></script>

<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>

<script src="<?php echo BASE_URL.'js/speechbubbles.js'?>"></script>

<script type="text/javascript">

jQuery(function($){ //on document.ready

 $('.addspeech').speechbubble()

})

</script>

<script type="text/javascript" src="<?php echo BASE_URL.'scripts/ajaxupload.js'?>"></script>

<script src="http://code.jquery.com/jquery-latest.js"></script>

<!-- SLIDING BACK TO TOP -->

<script language="javascript" type="text/javascript" src="<?php echo BASE_URL.'js/jquery.slideto.v1.1.js'?>"></script>

<script language="javascript" type="text/javascript">

var jqnctop = jQuery.noConflict();

jqnctop(document).ready(function(){

	jqnctop('a[name=slidetotop]').slideto({

		target : '#pagetop',

		speed  : 700

	});

});



$(window).scroll(function(){

	if($(window).scrollTop() > 200 ){

		$('#backtotop').fadeIn("slow");

	} else if($(window).scrollTop() < 200 ){

		$('#backtotop').fadeOut("fast");

	}

});

</script>



<link rel="stylesheet" type="text/css" href="<?php echo BASE_URL.'css/tabcontent.css'?>" />

<script type="text/javascript" src="<?php echo BASE_URL.'js/tabcontent.js'?>"></script>

<script language="javascript" type="text/javascript">

$(function() {

	var open = false;

	$('#footerSlideButton').click(function() {

		if(open === false) {

			document.getElementById('footerSlideText').style.display='block';

			$('#footerSlideContent').animate({ height: '50px' });

			$(this).css('backgroundPosition', 'bottom left');

			open = true;

		} else {

			document.getElementById('footerSlideText').style.display='none';

			$('#footerSlideContent').animate({ height: '0px' });

			$(this).css('backgroundPosition', 'top left');

			open = false;

		}

	});

});

</script>
<style type="text/css">

body {background-color:#FFFFFF}

</style>





</head>

<body>

<div style="clear:both"></div>

<!---------end header---------------------------->

<!--<div style="padding:10px; padding-top:50px; font-size:14px;" align="center">

    <p>Your activation is complete.</p>

    <p>An email has been sent to <b><?php echo $this->userdetails[3];?></b>. It contains a link that you need to click in order to activate your account and start using dbee.</p>

	<p>Please check your spam/junk folder if activation email has not landed in your Inbox within 10 minutes.</p>

    <p>See you soon on dbee :)</p>





    <img src="<?php echo BASE_URL; ?>timthumb.php?src=<?php echo BASE_URL; ?>images/<?php echo 'Koala.jpg' ?>&h=40&w=40&zc=1&q=100"  /><br>

</div>-->



<div style="padding:10px; padding-top:50px; font-size:14px;" align="center">

   

<?php

    

   //echo'<pre>';print_r($_SERVER['DOCUMENT_ROOT']);die;



  $url = 'http://cdn2.4rapiddev.com/wp-content/themes/4rapiddev/images/hoanhuynh-avatar.png';

  $dir =  $_SERVER['DOCUMENT_ROOT'].'/imagefacebook/';



//$url = "http://other-site/image.png";

//$dir = "/my/local/dir/";



$rfile = fopen($url, "r");

$lfile = fopen($dir . basename($url), "w");



while(!feof($url)) fwrite($lfile, fread($rfile, 1), 1);



fclose($rfile);

fclose($lfile);



 /*



  $file_url ='http://cdn2.4rapiddev.com/wp-content/themes/4rapiddev/images/authors/hoanhuynh.png';

  $save_to =  $_SERVER['DOCUMENT_ROOT'].'/imagefacebook/file.jpg';



 function download_remote_file_with_curl($file_url, $save_to)

	{

                

		$ch = curl_init();

		curl_setopt($ch, CURLOPT_POST, 0); 

		curl_setopt($ch,CURLOPT_URL,$file_url); 

		curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1); 

		$file_content = curl_exec($ch);

                //echo'hi';die;

		curl_close($ch);

		$downloaded_file = fopen($save_to, 'w');

		fwrite($downloaded_file, $file_content);

		fclose($downloaded_file);

                //echo'hi';

 

	}



 $abc = download_remote_file_with_curl($file_url,$save_to);





*/







/*



 function download_remote_file_with_fopen($file_url, $save_to)

	{

		$in=    fopen($file_url, "rb");

		$out=   fopen($save_to, "wb");

 

		while ($chunk = fread($in,8192))

		{

			fwrite($out, $chunk, 8192);

		}

 

		fclose($in);

		fclose($out);

	}



echo $abc = download_remote_file_with_fopen($file_url,$save_to);







 function file_get_contents_curl($url)

    {

     $ch = curl_init();

    

     curl_setopt($ch, CURLOPT_HEADER, 0);

     curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);

     curl_setopt($ch, CURLOPT_URL, $url);

     curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);

    

     $data = curl_exec($ch);

     curl_close($ch);

    

     return $data;

    }

*/



/********************************************************************************************************************/

		$request = $this->getRequest()->getParams();        

		$namespace = new Zend_Session_Namespace();

		//echo'<pre>';print_r($namespace->usersfacebookinfo);die('index');    

		$url =  $namespace->usersfacebookinfo[0]['pic_big'];

		$dir =  $_SERVER['DOCUMENT_ROOT'].'/images/imagefacebook/';

		/*

			$rfile = fopen($url, "r");

			$lfile = fopen($dir . basename($url), "w");

			while(!feof($url)) fwrite($lfile, fread($rfile, 1), 1);

			fclose($rfile);

			fclose($lfile);

		*/

		define('BUFSIZ', 4095);

		$rfile = fopen($url, 'r');

		$lfile = fopen($dir . basename($url), 'w');

		while(!feof($rfile))

		fwrite($lfile, fread($rfile, BUFSIZ), BUFSIZ);

		fclose($rfile);

		fclose($lfile);

		print_r($namespace->Username);

/*******************************************************************************************************************/



?>







</div>

	

		