<div style="width:546px; margin-left:auto; margin-right:auto;"><img src="<?php echo BASE_URL ?>/img/<?php echo $this->configuration->SiteLogo; ?>" width="546" height="375" /></div>
<div style="font-family:Verdana, Arial, Helvetica, sans-serif; font-size:14px; color:#000000; text-align:center; width:1000px; margin-left:auto; margin-right:auto;">
<p style="font-weight:bold; margin-bottom:10px"><strong>We are currently going through maintenance. Please check back in some time.</strong></p>
<p style="font-weight:bold; margin-bottom:10px"><strong>Thank you for your patience :-)</strong></p>
<!-- <p><a href="/">Click here to go back to home</a> </p> -->
</div>