<?php
/**
 * Login page view
 *  
 * @author Deepak Nagar
 */
//echo '<h3 id="forgetTitle">Forgotten Password?</h3>';
$ErrorMessage='';

if (count($this->message)>0) { 
	 $ErrorMessage ='<span class="loginErrorMsg"><i class="fa fa-warning"></i>'.$this->message[0].'</span>';

}
//echo $ErrorMessage; exit;
if(empty($this->okay)){
?>
	<form action="" method="post" id="forgetPassWrp">
	<dl>
		<?php echo $ErrorMessage; ?>
		<h3 id="username-label">Enter your registered email</h3>		
		<dd>
			<input type="text" name="adminEmail" placeholder="Enter email">
			
		</dd>
		<dt>
			<button  type="submit" name="submit" id="forgetPassBtn" value="SUBMIT" class="btn btn-yellow pull-right">Continue</button>
			<div class="forgetPass"><a href="<?php echo BASE_URL ?>/admin/login" class="forgetPass bcktopLogin" style=" margin-top: 9px;">Back to log in</a></div>
			<div class="clearfix"> </div>
		</dt>
	</dl>
	</form>
	<?php 
} 
else if($this->okay == 1)
{
	require_once 'includes/globalfileadmin.php';
	?>
	<form action="" method="post">
	<dl>
		<div class="forgotQues"><?php echo $securityquetion[$this->ques]; ?></div>
		<dd><input type="password" name="myanswer" placeholder="Your answer"><input type="hidden" name="myid" value="<?php echo rand(45982, 999999).$this->id; ?>"></dd>
		<dt>
			<input  type="submit" name="answer" value="SUBMIT" class="btn btn-yellow forgotPassbtn"> 
		</dt>
		<div class="clearfix"> </div>
	</dl>
	</form>
	<?php 
}
?>

