
<!-- <p><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'add'));?>">Add new user</a></p> -->
<form action="<?php echo $this->url(array('controller'=>'user','action'=>'add'));?>" method="POST">
<table style="width:650px;" border="0">
<tbody>
<tr style="height:30px;">
    <td>User Name</td>
    <td>:</td>
	<td><input type="text" name="username" id="username" value="" /></td>
	<td>&nbsp;</td>
  </tr>
  <tr style="height:30px;">
    <td>Email</td>
    <td>:</td>
	<td><input type="text" name="email" id="email" value="" /></td>
	<td>&nbsp;</td>
  </tr>
<tr><td colspan=4>&nbsp;</td></tr>	
<tr><td>&nbsp;</td><td>&nbsp;</td><td colspan=2><input type="submit" name="submit" value="Submit" /></td></tr>
</tbody>
</table>
</form>