<?php         
$this->title = "Import Users";
$this->headTitle($this->title);


?>


<div id="addusersDialog" title="Add Users to DBEE">
	<p class="validateTips">All form fields are required.</p>
 
	<form>
	<fieldset>
		<label for="name">Name</label>
		<input type="text" name="username" id="username" class="text ui-widget-content ui-corner-all" />
		<label for="email">Email</label>
		<input type="text" name="useremail" id="useremail" value="" class="text ui-widget-content ui-corner-all" />
		
	</fieldset>
	</form>
</div>



		
<table style="width:650px;" border="0">
<tbody>
	<tr><td colspan=2>Save users to database</td></tr>	
	<tr><td colspan=2>&nbsp;</td></tr>		
	<tr style="text-align:left;background-color:yellow;height:50px;">
	    <th id="im_addusers">Add Users</th>
	    <th>Import & Add from csv</th>
	</tr>	
	
	<tr><td colspan=2>&nbsp;</td></tr>	
	<tr><td colspan=2>Invite users to DBEE</td></tr>	
	<tr><td colspan=2>&nbsp;</td></tr>		
	


	<tr><td colspan=2>&nbsp;</td></tr>	

	
</tbody>
</table>